CREATE TABLE TMP_TRIPLE AS SELECT * FROM AE_I_EXT_E
WHERE TRANS_DATE LIKE '11-JUL-12'
AND EDIT_CLERK = 'CLARKDA';

UPDATE TMP_TRIPLE SET AMOUNT = AMOUNT * -2;

CREATE TABLE TMP_TRIPLE_UDF AS SELECT * FROM AE_I_EXT_E_UDF
WHERE TRANS_NO IN (SELECT TRANS_NO FROM TMP_TRIPLE);

alter table tmp_triple add custom001 varchar2(60);

UPDATE TMP_TRIPLE SET CUSTOM001 = (SELECT CUSTOM001 FROM TMP_TRIPLE_UDF WHERE TMP_TRIPLE.TRANS_NO = TMP_TRIPLE_UDF.TRANS_NO);

create or replace
procedure proc_fixtriple as
NUMTRANX_NUM NUMBER(16);
chrExte_cash_no		VARCHAR2(15);
chrExte_craft_code	VARCHAR2(25);
chrExte_inv_no		VARCHAR2(15);
chrExte_po_code		VARCHAR2(25);
chrExte_post_date	VARCHAR2(14);
chrExte_req_no		VARCHAR2(15);
chrExte_shop_person	VARCHAR2(15);
chrExte_trans_date	VARCHAR2(14);
chrExte_proposal	VARCHAR2(15);
chrExte_sort_code	VARCHAR2(15);
numExte_amount		NUMBER(10,2);
chrExte_login		VARCHAR2(15);
CHREXTE_BATCH_NO	VARCHAR2(15);
CHREXTE_SUBLEDGER_TYPE VARCHAR2(6);
CHREXTE_PAYMENT_DATE VARCHAR2(14);
CHREXTE_DESCRIPTION VARCHAR2(4000);
CHREXTE_INV_DATE VARCHAR2(14);
CHREXTE_POSTED_YN VARCHAR2(2);
CHREXTE_EDIT_DATE VARCHAR2(14);
CHREXTE_EDIT_CLERK VARCHAR2(20);
CHREXTE_SHOP VARCHAR2(7);
CHREXTE_CUSTOM001 VARCHAR2(15);
numTransNum       number(16);

CURSOR CUR_EXT_E IS
  SELECT SUBLEDGER_TYPE, REQ_NO, INV_NO, CASH_NO, BATCH_NO, PROPOSAL, SORT_CODE, CRAFT_CODE, AMOUNT, SHOP_PERSON, PAYMENT_DATE, DESCRIPTION, INV_DATE, TRANS_DATE, POST_DATE, POSTED_YN, EDIT_DATE, EDIT_CLERK, SHOP, PO_CODE, CUSTOM001
  FROM TMP_TRIPLE;

BEGIN

OPEN CUR_EXT_E;
LOOP
			FETCH CUR_EXT_E INTO CHREXTE_SUBLEDGER_TYPE, CHREXTE_REQ_NO, CHREXTE_INV_NO, CHREXTE_CASH_NO, CHREXTE_BATCH_NO, CHREXTE_PROPOSAL, CHREXTE_SORT_CODE, CHREXTE_CRAFT_CODE, NUMEXTE_AMOUNT,
                CHREXTE_SHOP_PERSON, CHREXTE_PAYMENT_DATE, CHREXTE_DESCRIPTION, CHREXTE_INV_DATE, CHREXTE_TRANS_DATE, CHREXTE_POST_DATE, CHREXTE_POSTED_YN, CHREXTE_EDIT_DATE, CHREXTE_EDIT_CLERK,
                CHREXTE_SHOP, CHREXTE_PO_CODE, CHREXTE_CUSTOM001;
      EXIT WHEN cur_ext_e%NOTFOUND;

TRANX_GEN('G',1,NUMTRANX_NUM);

INSERT INTO AE_I_EXT_E (TRANS_NO, SUBLEDGER_TYPE, REQ_NO, INV_NO, CASH_NO, BATCH_NO, PROPOSAL, SORT_CODE, CRAFT_CODE, AMOUNT, SHOP_PERSON, PAYMENT_DATE, DESCRIPTION, INV_DATE, TRANS_DATE,
POST_DATE, POSTED_YN, EDIT_DATE, EDIT_CLERK, SHOP, PO_CODE) VALUES
(NUMTRANX_NUM, CHREXTE_SUBLEDGER_TYPE, CHREXTE_REQ_NO, CHREXTE_INV_NO, CHREXTE_CASH_NO, CHREXTE_BATCH_NO, CHREXTE_PROPOSAL, CHREXTE_SORT_CODE, CHREXTE_CRAFT_CODE, NUMEXTE_AMOUNT,
 CHREXTE_SHOP_PERSON, CHREXTE_PAYMENT_DATE, CHREXTE_DESCRIPTION, CHREXTE_INV_DATE, SYSDATE, NULL, 'N', SYSDATE, 'ETRISKA', CHREXTE_SHOP, CHREXTE_PO_CODE);
numTransNum := NUMTRANX_NUM;

INSERT INTO AE_I_EXT_E_UDF (TRANS_NO, CUSTOM001)
VALUES  (numTransNum, CHREXTE_CUSTOM001);

END LOOP;
close cur_ext_e;

END PROC_FIXTRIPLE;
/
exec PROC_FIXTRIPLE();