SELECT ae_help.multitenant_id, ae_help.id, ae_help.sort_order, ae_help.edit_clerk, ae_help.edit_date, ae_help.description, ae_help.license, ae_help.title, ae_help.doc_id FROM ae_help WHERE ( (ae_help.license = 'OM') AND (ae_help.multitenant_id = 1) ) ORDER BY ae_help.multitenant_id, ae_help.id;

SELECT ae_document_version_series.multitenant_id, ae_document_version_series.doc_id, ae_document_version_series.doc_state, ae_document_version_series.doc_name, ae_document_version_series.long_desc, ae_document_version_series.created_at, ae_document_version_series.created_by, ae_document_version_series.checked_out_by, ae_document_version_series.type_id, ae_document_version_series.external_id, ae_document_version_series.version_yn, ae_document_version_series.fire_cloud_yn, ae_document_version_series.fire_cloud_id, ae_document_version_series.edit_date, ae_document_version_series.edit_clerk FROM ae_document_version_series WHERE ( (ae_document_version_series.multitenant_id = 1) AND (ae_document_version_series.doc_id = 'A3B91D4D-FCA2-4A81-BE0D-CF708582A8AA') AND (ae_document_version_series.multitenant_id = 1) );

SELECT ae_document_relationship.multitenant_id, ae_document_relationship.relationship_id, ae_document_relationship.relationship_type, ae_document_relationship.target_doc_id, ae_document_relationship.edit_date, ae_document_relationship.source_doc_id, ae_document_relationship.edit_clerk FROM ae_document_relationship WHERE ( (ae_document_relationship.relationship_id = 'A3B91D4D-FCA2-4A81-BE0D-CF708582A8AA') AND (ae_document_relationship.multitenant_id = 1) ) ORDER BY ae_document_relationship.multitenant_id, ae_document_relationship.relationship_id;

SELECT ae_document_tag.multitenant_id, ae_document_tag.doc_id, ae_document_tag.tag_id, ae_document_tag.edit_date, ae_document_tag.edit_clerk FROM ae_document_tag WHERE ( (ae_document_tag.doc_id = 'A3B91D4D-FCA2-4A81-BE0D-CF708582A8AA') AND (ae_document_tag.multitenant_id = 1) ) ORDER BY ae_document_tag.multitenant_id, ae_document_tag.doc_id, ae_document_tag.tag_id;

SELECT ae_document_version.edit_date, ae_document_version.checked_in_by, ae_document_version.mime_type, ae_document_version.content_id, ae_document_version.content_hash, ae_document_version.is_pwc, ae_document_version.doc_ver_id, ae_document_version.byte_length, ae_document_version.store_id, ae_document_version.doc_id, ae_document_version.repo_id, ae_document_version.edit_clerk, ae_document_version.checked_in_comment, ae_document_version.filename, ae_document_version.multitenant_id, ae_document_version.content_url, ae_document_version.version_label, ae_document_version.external_id FROM ae_document_version WHERE ( (ae_document_version.doc_id = 'A3B91D4D-FCA2-4A81-BE0D-CF708582A8AA') AND (ae_document_version.multitenant_id = 1) ) ORDER BY ae_document_version.edit_date;

SELECT ae_document_version.multitenant_id, ae_document_version.doc_id, ae_document_version.doc_ver_id, ae_document_version.content_id, ae_document_version.version_label, ae_document_version.is_pwc, ae_document_version.byte_length, ae_document_version.content_hash, ae_document_version.content_url, ae_document_version.repo_id, ae_document_version.checked_in_by, ae_document_version.checked_in_comment, ae_document_version.mime_type, ae_document_version.external_id, ae_document_version.store_id, ae_document_version.filename, ae_document_version.edit_date, ae_document_version.edit_clerk FROM ae_document_version WHERE ( (ae_document_version.multitenant_id = 1) AND (ae_document_version.doc_id = 'A3B91D4D-FCA2-4A81-BE0D-CF708582A8AA') AND (ae_document_version.doc_ver_id = '3652FBF8-5422-412B-8369-AA66F81260B6') AND (ae_document_version.multitenant_id = 1) );

SELECT ae_document_property.multitenant_id, ae_document_property.doc_id, ae_document_property.type_id, ae_document_property.type_prop_id, ae_document_property.seq, ae_document_property.edit_clerk, ae_document_property.edit_date, ae_document_property.prop_value FROM ae_document_property WHERE ( (ae_document_property.doc_id = 'A3B91D4D-FCA2-4A81-BE0D-CF708582A8AA') AND (ae_document_property.multitenant_id = 1) ) ORDER BY ae_document_property.multitenant_id, ae_document_property.doc_id, ae_document_property.type_id, ae_document_property.type_prop_id;

SELECT ae_document_property.multitenant_id, ae_document_property.doc_id, ae_document_property.type_id, ae_document_property.type_prop_id, ae_document_property.seq, ae_document_property.prop_value, ae_document_property.edit_date, ae_document_property.edit_clerk FROM ae_document_property WHERE ( (ae_document_property.multitenant_id = 1) AND (ae_document_property.doc_id = 'A3B91D4D-FCA2-4A81-BE0D-CF708582A8AA') AND (ae_document_property.type_id = 12) AND (ae_document_property.type_prop_id = 0) AND (ae_document_property.multitenant_id = 1) );

SELECT ae_document_property.multitenant_id, ae_document_property.doc_id, ae_document_property.type_id, ae_document_property.type_prop_id, ae_document_property.seq, ae_document_property.prop_value, ae_document_property.edit_date, ae_document_property.edit_clerk FROM ae_document_property WHERE ( (ae_document_property.multitenant_id = 1) AND (ae_document_property.doc_id = 'A3B91D4D-FCA2-4A81-BE0D-CF708582A8AA') AND (ae_document_property.type_id = 12) AND (ae_document_property.type_prop_id = 1) AND (ae_document_property.multitenant_id = 1) );

SELECT ae_document_property.multitenant_id, ae_document_property.doc_id, ae_document_property.type_id, ae_document_property.type_prop_id, ae_document_property.seq, ae_document_property.prop_value, ae_document_property.edit_date, ae_document_property.edit_clerk FROM ae_document_property WHERE ( (ae_document_property.multitenant_id = 1) AND (ae_document_property.doc_id = 'A3B91D4D-FCA2-4A81-BE0D-CF708582A8AA') AND (ae_document_property.type_id = 12) AND (ae_document_property.type_prop_id = 2) AND (ae_document_property.multitenant_id = 1) );

SELECT ae_document_property.multitenant_id, ae_document_property.doc_id, ae_document_property.type_id, ae_document_property.type_prop_id, ae_document_property.seq, ae_document_property.prop_value, ae_document_property.edit_date, ae_document_property.edit_clerk FROM ae_document_property WHERE ( (ae_document_property.multitenant_id = 1) AND (ae_document_property.doc_id = 'A3B91D4D-FCA2-4A81-BE0D-CF708582A8AA') AND (ae_document_property.type_id = 12) AND (ae_document_property.type_prop_id = 3) AND (ae_document_property.multitenant_id = 1) );

SELECT ae_document_property.multitenant_id, ae_document_property.doc_id, ae_document_property.type_id, ae_document_property.type_prop_id, ae_document_property.seq, ae_document_property.prop_value, ae_document_property.edit_date, ae_document_property.edit_clerk FROM ae_document_property WHERE ( (ae_document_property.multitenant_id = 1) AND (ae_document_property.doc_id = 'A3B91D4D-FCA2-4A81-BE0D-CF708582A8AA') AND (ae_document_property.type_id = 12) AND (ae_document_property.type_prop_id = 4) AND (ae_document_property.multitenant_id = 1) );

SELECT ae_document_ace.multitenant_id, ae_document_ace.doc_id, ae_document_ace.ace_id, ae_document_ace.perm_write, ae_document_ace.perm_read, ae_document_ace.role_id, ae_document_ace.edit_date, ae_document_ace.edit_clerk FROM ae_document_ace WHERE ( (ae_document_ace.doc_id = 'A3B91D4D-FCA2-4A81-BE0D-CF708582A8AA') AND (ae_document_ace.multitenant_id = 1) ) ORDER BY ae_document_ace.multitenant_id, ae_document_ace.doc_id, ae_document_ace.ace_id;

SELECT ae_artifact_link.multitenant_id, ae_artifact_link.doc_id, ae_artifact_link.link_tranx_num, ae_artifact_link.edit_date, ae_artifact_link.edit_clerk, ae_artifact_link.type_id FROM ae_artifact_link WHERE ( (ae_artifact_link.doc_id = 'A3B91D4D-FCA2-4A81-BE0D-CF708582A8AA') AND (ae_artifact_link.multitenant_id = 1) ) ORDER BY ae_artifact_link.multitenant_id, ae_artifact_link.doc_id, ae_artifact_link.link_tranx_num;

SELECT ae_document_state_hist.edit_date, ae_document_state_hist.edit_clerk, ae_document_state_hist.multitenant_id, ae_document_state_hist.doc_state, ae_document_state_hist.doc_id, ae_document_state_hist.seq FROM ae_document_state_hist WHERE ( (ae_document_state_hist.doc_id = 'A3B91D4D-FCA2-4A81-BE0D-CF708582A8AA') AND (ae_document_state_hist.multitenant_id = 1) ) ORDER BY ae_document_state_hist.edit_date DESC;

SELECT ae_document_version.multitenant_id, ae_document_version.doc_id, ae_document_version.doc_ver_id, ae_document_version.content_id, ae_document_version.version_label, ae_document_version.is_pwc, ae_document_version.byte_length, ae_document_version.content_hash, ae_document_version.content_url, ae_document_version.repo_id, ae_document_version.checked_in_by, ae_document_version.checked_in_comment, ae_document_version.mime_type, ae_document_version.external_id, ae_document_version.store_id, ae_document_version.filename, ae_document_version.edit_date, ae_document_version.edit_clerk FROM ae_document_version WHERE ( (ae_document_version.multitenant_id = 1) AND (ae_document_version.doc_id = 'A3B91D4D-FCA2-4A81-BE0D-CF708582A8AA') AND (ae_document_version.doc_ver_id = '3652FBF8-5422-412B-8369-AA66F81260B6') AND (ae_document_version.multitenant_id = 1) );

SELECT ae_trigger.multitenant_id, ae_trigger.tranx_num, ae_trigger.doc_id, ae_trigger.filter_table_name, ae_trigger.seq, ae_trigger.type, ae_trigger.edit_clerk, ae_trigger.schd_freq, ae_trigger.status_code, ae_trigger.description, ae_trigger.schd_next_date, ae_trigger.edit_date, ae_trigger.active, ae_trigger.instance_id FROM ae_trigger WHERE ( (ae_trigger.type = 'TEMPLATE') AND (ae_trigger.filter_table_name = 'AE_I_ADJ_E') AND (ae_trigger.active = 'Y') AND (ae_trigger.multitenant_id = 1) ) ORDER BY ae_trigger.multitenant_id, ae_trigger.tranx_num;

SELECT ae_help.multitenant_id, ae_help.id, ae_help.sort_order, ae_help.edit_clerk, ae_help.edit_date, ae_help.description, ae_help.license, ae_help.title, ae_help.doc_id FROM ae_help WHERE ( (ae_help.license = 'OM') AND (ae_help.multitenant_id = 1) ) ORDER BY ae_help.multitenant_id, ae_help.id;

SELECT ae_document_version_series.multitenant_id, ae_document_version_series.doc_id, ae_document_version_series.doc_state, ae_document_version_series.doc_name, ae_document_version_series.long_desc, ae_document_version_series.created_at, ae_document_version_series.created_by, ae_document_version_series.checked_out_by, ae_document_version_series.type_id, ae_document_version_series.external_id, ae_document_version_series.version_yn, ae_document_version_series.fire_cloud_yn, ae_document_version_series.fire_cloud_id, ae_document_version_series.edit_date, ae_document_version_series.edit_clerk FROM ae_document_version_series WHERE ( (ae_document_version_series.multitenant_id = 1) AND (ae_document_version_series.doc_id = 'A3B91D4D-FCA2-4A81-BE0D-CF708582A8AA') AND (ae_document_version_series.multitenant_id = 1) );

SELECT ae_document_relationship.multitenant_id, ae_document_relationship.relationship_id, ae_document_relationship.relationship_type, ae_document_relationship.target_doc_id, ae_document_relationship.edit_date, ae_document_relationship.source_doc_id, ae_document_relationship.edit_clerk FROM ae_document_relationship WHERE ( (ae_document_relationship.relationship_id = 'A3B91D4D-FCA2-4A81-BE0D-CF708582A8AA') AND (ae_document_relationship.multitenant_id = 1) ) ORDER BY ae_document_relationship.multitenant_id, ae_document_relationship.relationship_id;

SELECT ae_document_tag.multitenant_id, ae_document_tag.doc_id, ae_document_tag.tag_id, ae_document_tag.edit_date, ae_document_tag.edit_clerk FROM ae_document_tag WHERE ( (ae_document_tag.doc_id = 'A3B91D4D-FCA2-4A81-BE0D-CF708582A8AA') AND (ae_document_tag.multitenant_id = 1) ) ORDER BY ae_document_tag.multitenant_id, ae_document_tag.doc_id, ae_document_tag.tag_id;

SELECT ae_document_version.edit_date, ae_document_version.checked_in_by, ae_document_version.mime_type, ae_document_version.content_id, ae_document_version.content_hash, ae_document_version.is_pwc, ae_document_version.doc_ver_id, ae_document_version.byte_length, ae_document_version.store_id, ae_document_version.doc_id, ae_document_version.repo_id, ae_document_version.edit_clerk, ae_document_version.checked_in_comment, ae_document_version.filename, ae_document_version.multitenant_id, ae_document_version.content_url, ae_document_version.version_label, ae_document_version.external_id FROM ae_document_version WHERE ( (ae_document_version.doc_id = 'A3B91D4D-FCA2-4A81-BE0D-CF708582A8AA') AND (ae_document_version.multitenant_id = 1) ) ORDER BY ae_document_version.edit_date;

SELECT ae_document_version.multitenant_id, ae_document_version.doc_id, ae_document_version.doc_ver_id, ae_document_version.content_id, ae_document_version.version_label, ae_document_version.is_pwc, ae_document_version.byte_length, ae_document_version.content_hash, ae_document_version.content_url, ae_document_version.repo_id, ae_document_version.checked_in_by, ae_document_version.checked_in_comment, ae_document_version.mime_type, ae_document_version.external_id, ae_document_version.store_id, ae_document_version.filename, ae_document_version.edit_date, ae_document_version.edit_clerk FROM ae_document_version WHERE ( (ae_document_version.multitenant_id = 1) AND (ae_document_version.doc_id = 'A3B91D4D-FCA2-4A81-BE0D-CF708582A8AA') AND (ae_document_version.doc_ver_id = '3652FBF8-5422-412B-8369-AA66F81260B6') AND (ae_document_version.multitenant_id = 1) );

SELECT ae_document_property.multitenant_id, ae_document_property.doc_id, ae_document_property.type_id, ae_document_property.type_prop_id, ae_document_property.seq, ae_document_property.edit_clerk, ae_document_property.edit_date, ae_document_property.prop_value FROM ae_document_property WHERE ( (ae_document_property.doc_id = 'A3B91D4D-FCA2-4A81-BE0D-CF708582A8AA') AND (ae_document_property.multitenant_id = 1) ) ORDER BY ae_document_property.multitenant_id, ae_document_property.doc_id, ae_document_property.type_id, ae_document_property.type_prop_id;

SELECT ae_document_property.multitenant_id, ae_document_property.doc_id, ae_document_property.type_id, ae_document_property.type_prop_id, ae_document_property.seq, ae_document_property.prop_value, ae_document_property.edit_date, ae_document_property.edit_clerk FROM ae_document_property WHERE ( (ae_document_property.multitenant_id = 1) AND (ae_document_property.doc_id = 'A3B91D4D-FCA2-4A81-BE0D-CF708582A8AA') AND (ae_document_property.type_id = 12) AND (ae_document_property.type_prop_id = 0) AND (ae_document_property.multitenant_id = 1) );

SELECT ae_document_property.multitenant_id, ae_document_property.doc_id, ae_document_property.type_id, ae_document_property.type_prop_id, ae_document_property.seq, ae_document_property.prop_value, ae_document_property.edit_date, ae_document_property.edit_clerk FROM ae_document_property WHERE ( (ae_document_property.multitenant_id = 1) AND (ae_document_property.doc_id = 'A3B91D4D-FCA2-4A81-BE0D-CF708582A8AA') AND (ae_document_property.type_id = 12) AND (ae_document_property.type_prop_id = 1) AND (ae_document_property.multitenant_id = 1) );

SELECT ae_document_property.multitenant_id, ae_document_property.doc_id, ae_document_property.type_id, ae_document_property.type_prop_id, ae_document_property.seq, ae_document_property.prop_value, ae_document_property.edit_date, ae_document_property.edit_clerk FROM ae_document_property WHERE ( (ae_document_property.multitenant_id = 1) AND (ae_document_property.doc_id = 'A3B91D4D-FCA2-4A81-BE0D-CF708582A8AA') AND (ae_document_property.type_id = 12) AND (ae_document_property.type_prop_id = 2) AND (ae_document_property.multitenant_id = 1) );

SELECT ae_document_property.multitenant_id, ae_document_property.doc_id, ae_document_property.type_id, ae_document_property.type_prop_id, ae_document_property.seq, ae_document_property.prop_value, ae_document_property.edit_date, ae_document_property.edit_clerk FROM ae_document_property WHERE ( (ae_document_property.multitenant_id = 1) AND (ae_document_property.doc_id = 'A3B91D4D-FCA2-4A81-BE0D-CF708582A8AA') AND (ae_document_property.type_id = 12) AND (ae_document_property.type_prop_id = 3) AND (ae_document_property.multitenant_id = 1) );

SELECT ae_document_property.multitenant_id, ae_document_property.doc_id, ae_document_property.type_id, ae_document_property.type_prop_id, ae_document_property.seq, ae_document_property.prop_value, ae_document_property.edit_date, ae_document_property.edit_clerk FROM ae_document_property WHERE ( (ae_document_property.multitenant_id = 1) AND (ae_document_property.doc_id = 'A3B91D4D-FCA2-4A81-BE0D-CF708582A8AA') AND (ae_document_property.type_id = 12) AND (ae_document_property.type_prop_id = 4) AND (ae_document_property.multitenant_id = 1) );

SELECT ae_document_ace.multitenant_id, ae_document_ace.doc_id, ae_document_ace.ace_id, ae_document_ace.perm_write, ae_document_ace.perm_read, ae_document_ace.role_id, ae_document_ace.edit_date, ae_document_ace.edit_clerk FROM ae_document_ace WHERE ( (ae_document_ace.doc_id = 'A3B91D4D-FCA2-4A81-BE0D-CF708582A8AA') AND (ae_document_ace.multitenant_id = 1) ) ORDER BY ae_document_ace.multitenant_id, ae_document_ace.doc_id, ae_document_ace.ace_id;

SELECT ae_artifact_link.multitenant_id, ae_artifact_link.doc_id, ae_artifact_link.link_tranx_num, ae_artifact_link.edit_date, ae_artifact_link.edit_clerk, ae_artifact_link.type_id FROM ae_artifact_link WHERE ( (ae_artifact_link.doc_id = 'A3B91D4D-FCA2-4A81-BE0D-CF708582A8AA') AND (ae_artifact_link.multitenant_id = 1) ) ORDER BY ae_artifact_link.multitenant_id, ae_artifact_link.doc_id, ae_artifact_link.link_tranx_num;

SELECT ae_document_state_hist.edit_date, ae_document_state_hist.edit_clerk, ae_document_state_hist.multitenant_id, ae_document_state_hist.doc_state, ae_document_state_hist.doc_id, ae_document_state_hist.seq FROM ae_document_state_hist WHERE ( (ae_document_state_hist.doc_id = 'A3B91D4D-FCA2-4A81-BE0D-CF708582A8AA') AND (ae_document_state_hist.multitenant_id = 1) ) ORDER BY ae_document_state_hist.edit_date DESC;

SELECT ae_document_version.multitenant_id, ae_document_version.doc_id, ae_document_version.doc_ver_id, ae_document_version.content_id, ae_document_version.version_label, ae_document_version.is_pwc, ae_document_version.byte_length, ae_document_version.content_hash, ae_document_version.content_url, ae_document_version.repo_id, ae_document_version.checked_in_by, ae_document_version.checked_in_comment, ae_document_version.mime_type, ae_document_version.external_id, ae_document_version.store_id, ae_document_version.filename, ae_document_version.edit_date, ae_document_version.edit_clerk FROM ae_document_version WHERE ( (ae_document_version.multitenant_id = 1) AND (ae_document_version.doc_id = 'A3B91D4D-FCA2-4A81-BE0D-CF708582A8AA') AND (ae_document_version.doc_ver_id = '3652FBF8-5422-412B-8369-AA66F81260B6') AND (ae_document_version.multitenant_id = 1) );

SELECT ae_s_sec_c.multitenant_id, ae_s_sec_c.login, ae_s_sec_c.assigned_by, ae_s_sec_c.assign_date, ae_s_sec_c.description, ae_s_sec_c.password, ae_s_sec_c.order_type, ae_s_sec_c.category, ae_s_sec_c.region_code, ae_s_sec_c.fac_id, ae_s_sec_c.bldg, ae_s_sec_c.labor_class, ae_s_sec_c.shop, ae_s_sec_c.company_id, ae_s_sec_c.dept_id, ae_s_sec_c.oc_code, ae_s_sec_c.requestor, ae_s_sec_c.passwd_exp_days, ae_s_sec_c.passwd_last_change, ae_s_sec_c.contractor, ae_s_sec_c.crt_flag, ae_s_sec_c.warehouse, ae_s_sec_c.employee_id, ae_s_sec_c.mfm_download, ae_s_sec_c.edit_date, ae_s_sec_c.edit_clerk, ae_s_sec_c.default_org, ae_s_sec_c.loc_id, ae_s_sec_c.location_code, ae_s_sec_c.active, ae_s_sec_c.link_tranx_num, ae_s_sec_c.last_login, ae_s_sec_c.admin_id, ae_s_sec_c.email, ae_s_sec_c.authorizer, ae_s_sec_c.authorizer_email, ae_s_sec_c.login_attempt_count, ae_s_sec_c.rpd_flag, ae_s_sec_c.ssha_hash, ae_s_sec_c.salt, ae_s_sec_c.acessibility_flag, ae_s_sec_c.fire_bucket FROM ae_s_sec_c WHERE ( (ae_s_sec_c.multitenant_id = 1) AND (ae_s_sec_c.login = 'ETRISKA') AND (ae_s_sec_c.multitenant_id = 1) );

SELECT ae_h_emp_e.multitenant_id, ae_h_emp_e.shop_person, ae_h_emp_e.lname, ae_h_emp_e.fname, ae_h_emp_e.mi, ae_h_emp_e.user_id, ae_h_emp_e.emp_type, ae_h_emp_e.edit_date, ae_h_emp_e.edit_clerk, ae_h_emp_e.labor_class, ae_h_emp_e.time_type, ae_h_emp_e.active, ae_h_emp_e.link_tranx_num, ae_h_emp_e.doc_id FROM ae_h_emp_e WHERE ( (ae_h_emp_e.multitenant_id = 1) AND (ae_h_emp_e.shop_person = '0038') AND (ae_h_emp_e.multitenant_id = 1) );

SELECT ae_i_loc_e.multitenant_id, ae_i_loc_e.warehouse, ae_i_loc_e.bin_location, ae_i_loc_e.inv_maxlev, ae_i_loc_e.jan_tl, ae_i_loc_e.jul_rop, ae_i_loc_e.sep_roa, ae_i_loc_e.nov_roa, ae_i_loc_e.link_tranx_num, ae_i_loc_e.nov_tl, ae_i_loc_e.apr_rop, ae_i_loc_e.inv_minlev, ae_i_loc_e.edit_date, ae_i_loc_e.jun_rop, ae_i_loc_e.mar_tl, ae_i_loc_e.jan_rop, ae_i_loc_e.qty, ae_i_loc_e.active, ae_i_loc_e.aug_rop, ae_i_loc_e.oct_roa, ae_i_loc_e.reorder_qty, ae_i_loc_e.sched_freq, ae_i_loc_e.jun_tl, ae_i_loc_e.aug_tl, ae_i_loc_e.feb_rop, ae_i_loc_e.parent_bin, ae_i_loc_e.bin_order, ae_i_loc_e.jul_tl, ae_i_loc_e.mar_rop, ae_i_loc_e.feb_tl, ae_i_loc_e.may_rop, ae_i_loc_e.part, ae_i_loc_e.sep_tl, ae_i_loc_e.apr_roa, ae_i_loc_e.parent_warehouse, ae_i_loc_e.mar_roa, ae_i_loc_e.start_date, ae_i_loc_e.aug_roa, ae_i_loc_e.edit_clerk, ae_i_loc_e.jun_roa, ae_i_loc_e.dec_rop, ae_i_loc_e.dec_tl, ae_i_loc_e.description, ae_i_loc_e.oct_rop, ae_i_loc_e.feb_roa, ae_i_loc_e.may_roa, ae_i_loc_e.jan_roa, ae_i_loc_e.may_tl, ae_i_loc_e.target_level, ae_i_loc_e.reorder_level, ae_i_loc_e.dec_roa, ae_i_loc_e.apr_tl, ae_i_loc_e.oct_tl, ae_i_loc_e.jul_roa, ae_i_loc_e.nov_rop, ae_i_loc_e.sep_rop FROM ae_i_loc_e WHERE ( (ae_i_loc_e.warehouse = 'M2350') AND (ae_i_loc_e.part = '101682') AND (ae_i_loc_e.multitenant_id = 1) ) ORDER BY ae_i_loc_e.multitenant_id, ae_i_loc_e.warehouse, ae_i_loc_e.bin_location;

SELECT ae_i_inv_w.multitenant_id, ae_i_inv_w.part, ae_i_inv_w.warehouse, ae_i_inv_w.mark_up, ae_i_inv_w.markup_sub_code, ae_i_inv_w.edit_date, ae_i_inv_w.spec_cd_flag, ae_i_inv_w.whse_cost, ae_i_inv_w.markup_funding_code, ae_i_inv_w.edit_clerk, ae_i_inv_w.link_tranx_num FROM ae_i_inv_w WHERE ( (ae_i_inv_w.part = '101682') AND (ae_i_inv_w.warehouse = 'M2350') AND (ae_i_inv_w.multitenant_id = 1) ) ORDER BY ae_i_inv_w.multitenant_id, ae_i_inv_w.part, ae_i_inv_w.warehouse;

SELECT ae_trigger.multitenant_id, ae_trigger.tranx_num, ae_trigger.doc_id, ae_trigger.filter_table_name, ae_trigger.seq, ae_trigger.type, ae_trigger.edit_clerk, ae_trigger.schd_freq, ae_trigger.status_code, ae_trigger.description, ae_trigger.schd_next_date, ae_trigger.edit_date, ae_trigger.active, ae_trigger.instance_id FROM ae_trigger WHERE ( (ae_trigger.type = 'BEFORE_INSERT') AND (ae_trigger.filter_table_name = 'AE_I_ADJ_E') AND (ae_trigger.active = 'Y') AND (ae_trigger.multitenant_id = 1) ) ORDER BY ae_trigger.multitenant_id, ae_trigger.tranx_num;

SELECT 1 FROM DUAL WHERE 1 <= (SELECT COUNT(*)  FROM ae_i_adj_e WHERE ( (ae_i_adj_e.multitenant_id = 1) AND (ae_i_adj_e.trans_num = 25961) AND (ae_i_adj_e.multitenant_id = 1) ));

SELECT COUNT(*) FROM ae_i_whs_e WHERE ( (ae_i_whs_e.warehouse = 'M2350') AND (ae_i_whs_e.active = 'Y') AND (ae_i_whs_e.multitenant_id = 1) );

SELECT COUNT(*) FROM ae_i_inv_e WHERE ( (ae_i_inv_e.part = '101682') AND (ae_i_inv_e.multitenant_id = 1) );

SELECT ae_i_loc_e.multitenant_id, ae_i_loc_e.warehouse, ae_i_loc_e.bin_location, ae_i_loc_e.inv_maxlev, ae_i_loc_e.jan_tl, ae_i_loc_e.jul_rop, ae_i_loc_e.sep_roa, ae_i_loc_e.nov_roa, ae_i_loc_e.link_tranx_num, ae_i_loc_e.nov_tl, ae_i_loc_e.apr_rop, ae_i_loc_e.inv_minlev, ae_i_loc_e.edit_date, ae_i_loc_e.jun_rop, ae_i_loc_e.mar_tl, ae_i_loc_e.jan_rop, ae_i_loc_e.qty, ae_i_loc_e.active, ae_i_loc_e.aug_rop, ae_i_loc_e.oct_roa, ae_i_loc_e.reorder_qty, ae_i_loc_e.sched_freq, ae_i_loc_e.jun_tl, ae_i_loc_e.aug_tl, ae_i_loc_e.feb_rop, ae_i_loc_e.parent_bin, ae_i_loc_e.bin_order, ae_i_loc_e.jul_tl, ae_i_loc_e.mar_rop, ae_i_loc_e.feb_tl, ae_i_loc_e.may_rop, ae_i_loc_e.part, ae_i_loc_e.sep_tl, ae_i_loc_e.apr_roa, ae_i_loc_e.parent_warehouse, ae_i_loc_e.mar_roa, ae_i_loc_e.start_date, ae_i_loc_e.aug_roa, ae_i_loc_e.edit_clerk, ae_i_loc_e.jun_roa, ae_i_loc_e.dec_rop, ae_i_loc_e.dec_tl, ae_i_loc_e.description, ae_i_loc_e.oct_rop, ae_i_loc_e.feb_roa, ae_i_loc_e.may_roa, ae_i_loc_e.jan_roa, ae_i_loc_e.may_tl, ae_i_loc_e.target_level, ae_i_loc_e.reorder_level, ae_i_loc_e.dec_roa, ae_i_loc_e.apr_tl, ae_i_loc_e.oct_tl, ae_i_loc_e.jul_roa, ae_i_loc_e.nov_rop, ae_i_loc_e.sep_rop FROM ae_i_loc_e WHERE ( (ae_i_loc_e.warehouse = 'M2350') AND (ae_i_loc_e.part = '101682') AND (ae_i_loc_e.multitenant_id = 1) ) ORDER BY ae_i_loc_e.multitenant_id, ae_i_loc_e.warehouse, ae_i_loc_e.bin_location;

SELECT ae_i_inv_e.multitenant_id, ae_i_inv_e.comm_code, ae_i_inv_e.cycle_code, ae_i_inv_e.edit_date, ae_i_inv_e.inv_class, ae_i_inv_e.description, ae_i_inv_e.inv_uom, ae_i_inv_e.item_type, ae_i_inv_e.manufacture_code, ae_i_inv_e.model, ae_i_inv_e.part, ae_i_inv_e.edit_clerk, ae_i_inv_e.active, ae_i_inv_e.fraction_yn, ae_i_inv_e.inv_item, ae_i_inv_e.pmi_basic, ae_i_inv_e.long_desc, ae_i_inv_e.link_tranx_num, ae_i_inv_e.doc_id, ae_i_inv_e.msds_num, ae_i_inv_e.msds_required, ae_i_inv_e.green_yn FROM ae_i_inv_e WHERE ( (ae_i_inv_e.multitenant_id = 1) AND (ae_i_inv_e.part = '101682') AND (ae_i_inv_e.multitenant_id = 1) );

SELECT ae_trigger.multitenant_id, ae_trigger.tranx_num, ae_trigger.doc_id, ae_trigger.filter_table_name, ae_trigger.seq, ae_trigger.type, ae_trigger.edit_clerk, ae_trigger.schd_freq, ae_trigger.status_code, ae_trigger.description, ae_trigger.schd_next_date, ae_trigger.edit_date, ae_trigger.active, ae_trigger.instance_id FROM ae_trigger WHERE ( (ae_trigger.type = 'INSERT') AND (ae_trigger.filter_table_name = 'AE_I_ADJ_E') AND (ae_trigger.active = 'Y') AND (ae_trigger.multitenant_id = 1) ) ORDER BY ae_trigger.multitenant_id, ae_trigger.tranx_num;

INSERT INTO ae_i_adj_e (multitenant_id, trans_num, adjustment_type, description, warehouse, bin_location, part, inv_cost, adj_qty, edit_clerk, edit_date) VALUES (1, 25961, 'C', 'TEST', 'M2350', null, '101682', 54.08, null, 'ETRISKA', '2016-07-19 09:00:24');

SELECT ae_i_loc_e.multitenant_id, ae_i_loc_e.warehouse, ae_i_loc_e.bin_location, ae_i_loc_e.inv_maxlev, ae_i_loc_e.jan_tl, ae_i_loc_e.jul_rop, ae_i_loc_e.sep_roa, ae_i_loc_e.nov_roa, ae_i_loc_e.link_tranx_num, ae_i_loc_e.nov_tl, ae_i_loc_e.apr_rop, ae_i_loc_e.inv_minlev, ae_i_loc_e.edit_date, ae_i_loc_e.jun_rop, ae_i_loc_e.mar_tl, ae_i_loc_e.jan_rop, ae_i_loc_e.qty, ae_i_loc_e.active, ae_i_loc_e.aug_rop, ae_i_loc_e.oct_roa, ae_i_loc_e.reorder_qty, ae_i_loc_e.sched_freq, ae_i_loc_e.jun_tl, ae_i_loc_e.aug_tl, ae_i_loc_e.feb_rop, ae_i_loc_e.parent_bin, ae_i_loc_e.bin_order, ae_i_loc_e.jul_tl, ae_i_loc_e.mar_rop, ae_i_loc_e.feb_tl, ae_i_loc_e.may_rop, ae_i_loc_e.part, ae_i_loc_e.sep_tl, ae_i_loc_e.apr_roa, ae_i_loc_e.parent_warehouse, ae_i_loc_e.mar_roa, ae_i_loc_e.start_date, ae_i_loc_e.aug_roa, ae_i_loc_e.edit_clerk, ae_i_loc_e.jun_roa, ae_i_loc_e.dec_rop, ae_i_loc_e.dec_tl, ae_i_loc_e.description, ae_i_loc_e.oct_rop, ae_i_loc_e.feb_roa, ae_i_loc_e.may_roa, ae_i_loc_e.jan_roa, ae_i_loc_e.may_tl, ae_i_loc_e.target_level, ae_i_loc_e.reorder_level, ae_i_loc_e.dec_roa, ae_i_loc_e.apr_tl, ae_i_loc_e.oct_tl, ae_i_loc_e.jul_roa, ae_i_loc_e.nov_rop, ae_i_loc_e.sep_rop FROM ae_i_loc_e WHERE ( (ae_i_loc_e.warehouse = 'M2350') AND (ae_i_loc_e.part = '101682') AND (ae_i_loc_e.multitenant_id = 1) ) ORDER BY ae_i_loc_e.multitenant_id, ae_i_loc_e.warehouse, ae_i_loc_e.bin_location;

SELECT ae_i_loc_e.multitenant_id, ae_i_loc_e.warehouse, ae_i_loc_e.bin_location, ae_i_loc_e.description, ae_i_loc_e.part, ae_i_loc_e.qty, ae_i_loc_e.start_date, ae_i_loc_e.sched_freq, ae_i_loc_e.parent_bin, ae_i_loc_e.parent_warehouse, ae_i_loc_e.inv_minlev, ae_i_loc_e.inv_maxlev, ae_i_loc_e.reorder_level, ae_i_loc_e.bin_order, ae_i_loc_e.reorder_qty, ae_i_loc_e.edit_date, ae_i_loc_e.edit_clerk, ae_i_loc_e.jan_rop, ae_i_loc_e.feb_rop, ae_i_loc_e.mar_rop, ae_i_loc_e.apr_rop, ae_i_loc_e.may_rop, ae_i_loc_e.jun_rop, ae_i_loc_e.jul_rop, ae_i_loc_e.aug_rop, ae_i_loc_e.sep_rop, ae_i_loc_e.oct_rop, ae_i_loc_e.nov_rop, ae_i_loc_e.dec_rop, ae_i_loc_e.jan_roa, ae_i_loc_e.feb_roa, ae_i_loc_e.mar_roa, ae_i_loc_e.apr_roa, ae_i_loc_e.may_roa, ae_i_loc_e.jun_roa, ae_i_loc_e.jul_roa, ae_i_loc_e.aug_roa, ae_i_loc_e.sep_roa, ae_i_loc_e.oct_roa, ae_i_loc_e.nov_roa, ae_i_loc_e.dec_roa, ae_i_loc_e.link_tranx_num, ae_i_loc_e.active, ae_i_loc_e.target_level, ae_i_loc_e.jan_tl, ae_i_loc_e.feb_tl, ae_i_loc_e.mar_tl, ae_i_loc_e.apr_tl, ae_i_loc_e.may_tl, ae_i_loc_e.jun_tl, ae_i_loc_e.jul_tl, ae_i_loc_e.aug_tl, ae_i_loc_e.sep_tl, ae_i_loc_e.oct_tl, ae_i_loc_e.nov_tl, ae_i_loc_e.dec_tl FROM ae_i_loc_e WHERE ( (ae_i_loc_e.multitenant_id = 1) AND (ae_i_loc_e.warehouse = 'M2350') AND (ae_i_loc_e.bin_location = 'UNIT1.B.2.2') AND (ae_i_loc_e.multitenant_id = 1) );

SELECT ae_i_inv_w.multitenant_id, ae_i_inv_w.part, ae_i_inv_w.warehouse, ae_i_inv_w.spec_cd_flag, ae_i_inv_w.mark_up, ae_i_inv_w.markup_funding_code, ae_i_inv_w.whse_cost, ae_i_inv_w.markup_sub_code, ae_i_inv_w.edit_date, ae_i_inv_w.edit_clerk, ae_i_inv_w.link_tranx_num FROM ae_i_inv_w WHERE ( (ae_i_inv_w.multitenant_id = 1) AND (ae_i_inv_w.part = '101682') AND (ae_i_inv_w.warehouse = 'M2350') AND (ae_i_inv_w.multitenant_id = 1) );

SELECT ae_i_loc_e.multitenant_id, ae_i_loc_e.warehouse, ae_i_loc_e.bin_location, ae_i_loc_e.description, ae_i_loc_e.part, ae_i_loc_e.qty, ae_i_loc_e.start_date, ae_i_loc_e.sched_freq, ae_i_loc_e.parent_bin, ae_i_loc_e.parent_warehouse, ae_i_loc_e.inv_minlev, ae_i_loc_e.inv_maxlev, ae_i_loc_e.reorder_level, ae_i_loc_e.bin_order, ae_i_loc_e.reorder_qty, ae_i_loc_e.edit_date, ae_i_loc_e.edit_clerk, ae_i_loc_e.jan_rop, ae_i_loc_e.feb_rop, ae_i_loc_e.mar_rop, ae_i_loc_e.apr_rop, ae_i_loc_e.may_rop, ae_i_loc_e.jun_rop, ae_i_loc_e.jul_rop, ae_i_loc_e.aug_rop, ae_i_loc_e.sep_rop, ae_i_loc_e.oct_rop, ae_i_loc_e.nov_rop, ae_i_loc_e.dec_rop, ae_i_loc_e.jan_roa, ae_i_loc_e.feb_roa, ae_i_loc_e.mar_roa, ae_i_loc_e.apr_roa, ae_i_loc_e.may_roa, ae_i_loc_e.jun_roa, ae_i_loc_e.jul_roa, ae_i_loc_e.aug_roa, ae_i_loc_e.sep_roa, ae_i_loc_e.oct_roa, ae_i_loc_e.nov_roa, ae_i_loc_e.dec_roa, ae_i_loc_e.link_tranx_num, ae_i_loc_e.active, ae_i_loc_e.target_level, ae_i_loc_e.jan_tl, ae_i_loc_e.feb_tl, ae_i_loc_e.mar_tl, ae_i_loc_e.apr_tl, ae_i_loc_e.may_tl, ae_i_loc_e.jun_tl, ae_i_loc_e.jul_tl, ae_i_loc_e.aug_tl, ae_i_loc_e.sep_tl, ae_i_loc_e.oct_tl, ae_i_loc_e.nov_tl, ae_i_loc_e.dec_tl FROM ae_i_loc_e WHERE ( (ae_i_loc_e.multitenant_id = 1) AND (ae_i_loc_e.warehouse = 'M2350') AND (ae_i_loc_e.bin_location = 'UNIT1.B.2.2') AND (ae_i_loc_e.multitenant_id = 1) );

SELECT 1 FROM DUAL WHERE 1 <= (SELECT COUNT(*)  FROM ae_i_trans_reg WHERE ( (ae_i_trans_reg.multitenant_id = 1) AND (ae_i_trans_reg.trans_num = 241880) AND (ae_i_trans_reg.multitenant_id = 1) ));

SELECT COUNT(*) FROM ae_i_whs_e WHERE ( (ae_i_whs_e.warehouse = 'M2350') AND (ae_i_whs_e.active = 'Y') AND (ae_i_whs_e.multitenant_id = 1) );

SELECT COUNT(*) FROM ae_i_inv_e WHERE ( (ae_i_inv_e.part = '101682') AND (ae_i_inv_e.multitenant_id = 1) );

SELECT ae_i_loc_e.multitenant_id, ae_i_loc_e.warehouse, ae_i_loc_e.bin_location, ae_i_loc_e.inv_maxlev, ae_i_loc_e.jan_tl, ae_i_loc_e.jul_rop, ae_i_loc_e.sep_roa, ae_i_loc_e.nov_roa, ae_i_loc_e.link_tranx_num, ae_i_loc_e.nov_tl, ae_i_loc_e.apr_rop, ae_i_loc_e.inv_minlev, ae_i_loc_e.edit_date, ae_i_loc_e.jun_rop, ae_i_loc_e.mar_tl, ae_i_loc_e.jan_rop, ae_i_loc_e.qty, ae_i_loc_e.active, ae_i_loc_e.aug_rop, ae_i_loc_e.oct_roa, ae_i_loc_e.reorder_qty, ae_i_loc_e.sched_freq, ae_i_loc_e.jun_tl, ae_i_loc_e.aug_tl, ae_i_loc_e.feb_rop, ae_i_loc_e.parent_bin, ae_i_loc_e.bin_order, ae_i_loc_e.jul_tl, ae_i_loc_e.mar_rop, ae_i_loc_e.feb_tl, ae_i_loc_e.may_rop, ae_i_loc_e.part, ae_i_loc_e.sep_tl, ae_i_loc_e.apr_roa, ae_i_loc_e.parent_warehouse, ae_i_loc_e.mar_roa, ae_i_loc_e.start_date, ae_i_loc_e.aug_roa, ae_i_loc_e.edit_clerk, ae_i_loc_e.jun_roa, ae_i_loc_e.dec_rop, ae_i_loc_e.dec_tl, ae_i_loc_e.description, ae_i_loc_e.oct_rop, ae_i_loc_e.feb_roa, ae_i_loc_e.may_roa, ae_i_loc_e.jan_roa, ae_i_loc_e.may_tl, ae_i_loc_e.target_level, ae_i_loc_e.reorder_level, ae_i_loc_e.dec_roa, ae_i_loc_e.apr_tl, ae_i_loc_e.oct_tl, ae_i_loc_e.jul_roa, ae_i_loc_e.nov_rop, ae_i_loc_e.sep_rop FROM ae_i_loc_e WHERE ( (ae_i_loc_e.warehouse = 'M2350') AND (ae_i_loc_e.bin_location = 'UNIT1.B.2.2') AND (ae_i_loc_e.part = '101682') AND (ae_i_loc_e.multitenant_id = 1) ) ORDER BY ae_i_loc_e.multitenant_id, ae_i_loc_e.warehouse, ae_i_loc_e.bin_location;

SELECT ae_trigger.multitenant_id, ae_trigger.tranx_num, ae_trigger.doc_id, ae_trigger.filter_table_name, ae_trigger.seq, ae_trigger.type, ae_trigger.edit_clerk, ae_trigger.schd_freq, ae_trigger.status_code, ae_trigger.description, ae_trigger.schd_next_date, ae_trigger.edit_date, ae_trigger.active, ae_trigger.instance_id FROM ae_trigger WHERE ( (ae_trigger.type = 'INSERT') AND (ae_trigger.filter_table_name = 'AE_I_TRANS_REG') AND (ae_trigger.active = 'Y') AND (ae_trigger.multitenant_id = 1) ) ORDER BY ae_trigger.multitenant_id, ae_trigger.tranx_num;

INSERT INTO ae_i_trans_reg (multitenant_id, trans_num, source_screenname, source_tranx_no, source_tranx_item, warehouse, bin_location, part, inv_cost, bin_qty, trans_qty, dollar_adj, entry_clerk, entry_date, edit_clerk, edit_date, description, vend_cost, issue_factor, eqp_tag_id, asset_tag, sub_line_seq) VALUES (1, 241880, 'INVENTORY ADJUSTMENT', 25961, 0, 'M2350', 'UNIT1.B.2.2', '101682', 0.01, null, -2, 0, 'ETRISKA', '2016-07-19 09:00:24', 'ETRISKA', '2016-07-19 09:00:24', 'INVENTORY PRICE ADJUSTEMENT', null, null, null, null, 0);

SELECT ae_i_inv_e.multitenant_id, ae_i_inv_e.comm_code, ae_i_inv_e.cycle_code, ae_i_inv_e.edit_date, ae_i_inv_e.inv_class, ae_i_inv_e.description, ae_i_inv_e.inv_uom, ae_i_inv_e.item_type, ae_i_inv_e.manufacture_code, ae_i_inv_e.model, ae_i_inv_e.part, ae_i_inv_e.edit_clerk, ae_i_inv_e.active, ae_i_inv_e.fraction_yn, ae_i_inv_e.inv_item, ae_i_inv_e.pmi_basic, ae_i_inv_e.long_desc, ae_i_inv_e.link_tranx_num, ae_i_inv_e.doc_id, ae_i_inv_e.msds_num, ae_i_inv_e.msds_required, ae_i_inv_e.green_yn FROM ae_i_inv_e WHERE ( (ae_i_inv_e.multitenant_id = 1) AND (ae_i_inv_e.part = '101682') AND (ae_i_inv_e.multitenant_id = 1) );

SELECT ae_i_inv_w.multitenant_id, ae_i_inv_w.part, ae_i_inv_w.warehouse, ae_i_inv_w.mark_up, ae_i_inv_w.markup_sub_code, ae_i_inv_w.edit_date, ae_i_inv_w.spec_cd_flag, ae_i_inv_w.whse_cost, ae_i_inv_w.markup_funding_code, ae_i_inv_w.edit_clerk, ae_i_inv_w.link_tranx_num FROM ae_i_inv_w WHERE ( (ae_i_inv_w.part = '101682') AND (ae_i_inv_w.warehouse = 'M2350') AND (ae_i_inv_w.multitenant_id = 1) ) ORDER BY ae_i_inv_w.multitenant_id, ae_i_inv_w.part, ae_i_inv_w.warehouse;

SELECT ae_i_loc_e.multitenant_id, ae_i_loc_e.warehouse, ae_i_loc_e.bin_location, ae_i_loc_e.description, ae_i_loc_e.part, ae_i_loc_e.qty, ae_i_loc_e.start_date, ae_i_loc_e.sched_freq, ae_i_loc_e.parent_bin, ae_i_loc_e.parent_warehouse, ae_i_loc_e.inv_minlev, ae_i_loc_e.inv_maxlev, ae_i_loc_e.reorder_level, ae_i_loc_e.bin_order, ae_i_loc_e.reorder_qty, ae_i_loc_e.edit_date, ae_i_loc_e.edit_clerk, ae_i_loc_e.jan_rop, ae_i_loc_e.feb_rop, ae_i_loc_e.mar_rop, ae_i_loc_e.apr_rop, ae_i_loc_e.may_rop, ae_i_loc_e.jun_rop, ae_i_loc_e.jul_rop, ae_i_loc_e.aug_rop, ae_i_loc_e.sep_rop, ae_i_loc_e.oct_rop, ae_i_loc_e.nov_rop, ae_i_loc_e.dec_rop, ae_i_loc_e.jan_roa, ae_i_loc_e.feb_roa, ae_i_loc_e.mar_roa, ae_i_loc_e.apr_roa, ae_i_loc_e.may_roa, ae_i_loc_e.jun_roa, ae_i_loc_e.jul_roa, ae_i_loc_e.aug_roa, ae_i_loc_e.sep_roa, ae_i_loc_e.oct_roa, ae_i_loc_e.nov_roa, ae_i_loc_e.dec_roa, ae_i_loc_e.link_tranx_num, ae_i_loc_e.active, ae_i_loc_e.target_level, ae_i_loc_e.jan_tl, ae_i_loc_e.feb_tl, ae_i_loc_e.mar_tl, ae_i_loc_e.apr_tl, ae_i_loc_e.may_tl, ae_i_loc_e.jun_tl, ae_i_loc_e.jul_tl, ae_i_loc_e.aug_tl, ae_i_loc_e.sep_tl, ae_i_loc_e.oct_tl, ae_i_loc_e.nov_tl, ae_i_loc_e.dec_tl FROM ae_i_loc_e WHERE ( (ae_i_loc_e.multitenant_id = 1) AND (ae_i_loc_e.warehouse = 'M2350') AND (ae_i_loc_e.bin_location = 'UNIT1.B.2.2') AND (ae_i_loc_e.multitenant_id = 1) );

SELECT ae_i_loc_e.multitenant_id, ae_i_loc_e.warehouse, ae_i_loc_e.bin_location, ae_i_loc_e.description, ae_i_loc_e.part, ae_i_loc_e.qty, ae_i_loc_e.start_date, ae_i_loc_e.sched_freq, ae_i_loc_e.parent_bin, ae_i_loc_e.parent_warehouse, ae_i_loc_e.inv_minlev, ae_i_loc_e.inv_maxlev, ae_i_loc_e.reorder_level, ae_i_loc_e.bin_order, ae_i_loc_e.reorder_qty, ae_i_loc_e.edit_date, ae_i_loc_e.edit_clerk, ae_i_loc_e.jan_rop, ae_i_loc_e.feb_rop, ae_i_loc_e.mar_rop, ae_i_loc_e.apr_rop, ae_i_loc_e.may_rop, ae_i_loc_e.jun_rop, ae_i_loc_e.jul_rop, ae_i_loc_e.aug_rop, ae_i_loc_e.sep_rop, ae_i_loc_e.oct_rop, ae_i_loc_e.nov_rop, ae_i_loc_e.dec_rop, ae_i_loc_e.jan_roa, ae_i_loc_e.feb_roa, ae_i_loc_e.mar_roa, ae_i_loc_e.apr_roa, ae_i_loc_e.may_roa, ae_i_loc_e.jun_roa, ae_i_loc_e.jul_roa, ae_i_loc_e.aug_roa, ae_i_loc_e.sep_roa, ae_i_loc_e.oct_roa, ae_i_loc_e.nov_roa, ae_i_loc_e.dec_roa, ae_i_loc_e.link_tranx_num, ae_i_loc_e.active, ae_i_loc_e.target_level, ae_i_loc_e.jan_tl, ae_i_loc_e.feb_tl, ae_i_loc_e.mar_tl, ae_i_loc_e.apr_tl, ae_i_loc_e.may_tl, ae_i_loc_e.jun_tl, ae_i_loc_e.jul_tl, ae_i_loc_e.aug_tl, ae_i_loc_e.sep_tl, ae_i_loc_e.oct_tl, ae_i_loc_e.nov_tl, ae_i_loc_e.dec_tl FROM ae_i_loc_e WHERE ( (ae_i_loc_e.multitenant_id = 1) AND (ae_i_loc_e.warehouse = 'M2350') AND (ae_i_loc_e.bin_location = 'UNIT1.B.2.2') AND (ae_i_loc_e.multitenant_id = 1) );

UPDATE ae_i_loc_e SET qty = 0, edit_date = '2016-07-19 09:00:24', edit_clerk = 'ETRISKA' WHERE ( (ae_i_loc_e.multitenant_id = 1) AND (ae_i_loc_e.warehouse = 'M2350') AND (ae_i_loc_e.bin_location = 'UNIT1.B.2.2') AND (ae_i_loc_e.multitenant_id = 1) );

SELECT ae_trigger.multitenant_id, ae_trigger.tranx_num, ae_trigger.doc_id, ae_trigger.filter_table_name, ae_trigger.seq, ae_trigger.type, ae_trigger.edit_clerk, ae_trigger.schd_freq, ae_trigger.status_code, ae_trigger.description, ae_trigger.schd_next_date, ae_trigger.edit_date, ae_trigger.active, ae_trigger.instance_id FROM ae_trigger WHERE ( (ae_trigger.type = 'UPDATE') AND (ae_trigger.filter_table_name = 'AE_I_LOC_E') AND (ae_trigger.active = 'Y') AND (ae_trigger.multitenant_id = 1) ) ORDER BY ae_trigger.multitenant_id, ae_trigger.tranx_num;

SELECT ae_i_inv_e.multitenant_id, ae_i_inv_e.comm_code, ae_i_inv_e.cycle_code, ae_i_inv_e.edit_date, ae_i_inv_e.inv_class, ae_i_inv_e.description, ae_i_inv_e.inv_uom, ae_i_inv_e.item_type, ae_i_inv_e.manufacture_code, ae_i_inv_e.model, ae_i_inv_e.part, ae_i_inv_e.edit_clerk, ae_i_inv_e.active, ae_i_inv_e.fraction_yn, ae_i_inv_e.inv_item, ae_i_inv_e.pmi_basic, ae_i_inv_e.long_desc, ae_i_inv_e.link_tranx_num, ae_i_inv_e.doc_id, ae_i_inv_e.msds_num, ae_i_inv_e.msds_required, ae_i_inv_e.green_yn FROM ae_i_inv_e WHERE ( (ae_i_inv_e.multitenant_id = 1) AND (ae_i_inv_e.part = '101682') AND (ae_i_inv_e.multitenant_id = 1) );

SELECT ae_i_inv_w.multitenant_id, ae_i_inv_w.part, ae_i_inv_w.warehouse, ae_i_inv_w.spec_cd_flag, ae_i_inv_w.mark_up, ae_i_inv_w.markup_funding_code, ae_i_inv_w.whse_cost, ae_i_inv_w.markup_sub_code, ae_i_inv_w.edit_date, ae_i_inv_w.edit_clerk, ae_i_inv_w.link_tranx_num FROM ae_i_inv_w WHERE ( (ae_i_inv_w.multitenant_id = 1) AND (ae_i_inv_w.part = '101682') AND (ae_i_inv_w.warehouse = 'M2350') AND (ae_i_inv_w.multitenant_id = 1) );

SELECT ae_i_inv_w.multitenant_id, ae_i_inv_w.part, ae_i_inv_w.warehouse, ae_i_inv_w.spec_cd_flag, ae_i_inv_w.mark_up, ae_i_inv_w.markup_funding_code, ae_i_inv_w.whse_cost, ae_i_inv_w.markup_sub_code, ae_i_inv_w.edit_date, ae_i_inv_w.edit_clerk, ae_i_inv_w.link_tranx_num FROM ae_i_inv_w WHERE ( (ae_i_inv_w.multitenant_id = 1) AND (ae_i_inv_w.part = '101682') AND (ae_i_inv_w.warehouse = 'M2350') AND (ae_i_inv_w.multitenant_id = 1) );

UPDATE ae_i_inv_w SET whse_cost = 0, edit_date = '2016-07-19 09:00:24', edit_clerk = 'ETRISKA' WHERE ( (ae_i_inv_w.multitenant_id = 1) AND (ae_i_inv_w.part = '101682') AND (ae_i_inv_w.warehouse = 'M2350') AND (ae_i_inv_w.multitenant_id = 1) );

SELECT ae_trigger.multitenant_id, ae_trigger.tranx_num, ae_trigger.doc_id, ae_trigger.filter_table_name, ae_trigger.seq, ae_trigger.type, ae_trigger.edit_clerk, ae_trigger.schd_freq, ae_trigger.status_code, ae_trigger.description, ae_trigger.schd_next_date, ae_trigger.edit_date, ae_trigger.active, ae_trigger.instance_id FROM ae_trigger WHERE ( (ae_trigger.type = 'UPDATE') AND (ae_trigger.filter_table_name = 'AE_I_INV_W') AND (ae_trigger.active = 'Y') AND (ae_trigger.multitenant_id = 1) ) ORDER BY ae_trigger.multitenant_id, ae_trigger.tranx_num;

SELECT ae_i_loc_e.multitenant_id, ae_i_loc_e.warehouse, ae_i_loc_e.bin_location, ae_i_loc_e.description, ae_i_loc_e.part, ae_i_loc_e.qty, ae_i_loc_e.start_date, ae_i_loc_e.sched_freq, ae_i_loc_e.parent_bin, ae_i_loc_e.parent_warehouse, ae_i_loc_e.inv_minlev, ae_i_loc_e.inv_maxlev, ae_i_loc_e.reorder_level, ae_i_loc_e.bin_order, ae_i_loc_e.reorder_qty, ae_i_loc_e.edit_date, ae_i_loc_e.edit_clerk, ae_i_loc_e.jan_rop, ae_i_loc_e.feb_rop, ae_i_loc_e.mar_rop, ae_i_loc_e.apr_rop, ae_i_loc_e.may_rop, ae_i_loc_e.jun_rop, ae_i_loc_e.jul_rop, ae_i_loc_e.aug_rop, ae_i_loc_e.sep_rop, ae_i_loc_e.oct_rop, ae_i_loc_e.nov_rop, ae_i_loc_e.dec_rop, ae_i_loc_e.jan_roa, ae_i_loc_e.feb_roa, ae_i_loc_e.mar_roa, ae_i_loc_e.apr_roa, ae_i_loc_e.may_roa, ae_i_loc_e.jun_roa, ae_i_loc_e.jul_roa, ae_i_loc_e.aug_roa, ae_i_loc_e.sep_roa, ae_i_loc_e.oct_roa, ae_i_loc_e.nov_roa, ae_i_loc_e.dec_roa, ae_i_loc_e.link_tranx_num, ae_i_loc_e.active, ae_i_loc_e.target_level, ae_i_loc_e.jan_tl, ae_i_loc_e.feb_tl, ae_i_loc_e.mar_tl, ae_i_loc_e.apr_tl, ae_i_loc_e.may_tl, ae_i_loc_e.jun_tl, ae_i_loc_e.jul_tl, ae_i_loc_e.aug_tl, ae_i_loc_e.sep_tl, ae_i_loc_e.oct_tl, ae_i_loc_e.nov_tl, ae_i_loc_e.dec_tl FROM ae_i_loc_e WHERE ( (ae_i_loc_e.multitenant_id = 1) AND (ae_i_loc_e.warehouse = 'M2350') AND (ae_i_loc_e.bin_location = 'UNIT1.B.2.2') AND (ae_i_loc_e.multitenant_id = 1) );

SELECT ae_i_inv_w.multitenant_id, ae_i_inv_w.part, ae_i_inv_w.warehouse, ae_i_inv_w.spec_cd_flag, ae_i_inv_w.mark_up, ae_i_inv_w.markup_funding_code, ae_i_inv_w.whse_cost, ae_i_inv_w.markup_sub_code, ae_i_inv_w.edit_date, ae_i_inv_w.edit_clerk, ae_i_inv_w.link_tranx_num FROM ae_i_inv_w WHERE ( (ae_i_inv_w.multitenant_id = 1) AND (ae_i_inv_w.part = '101682') AND (ae_i_inv_w.warehouse = 'M2350') AND (ae_i_inv_w.multitenant_id = 1) );

SELECT 1 FROM DUAL WHERE 1 <= (SELECT COUNT(*)  FROM ae_i_trans_reg WHERE ( (ae_i_trans_reg.multitenant_id = 1) AND (ae_i_trans_reg.trans_num = 241881) AND (ae_i_trans_reg.multitenant_id = 1) ));

SELECT COUNT(*) FROM ae_i_whs_e WHERE ( (ae_i_whs_e.warehouse = 'M2350') AND (ae_i_whs_e.active = 'Y') AND (ae_i_whs_e.multitenant_id = 1) );

SELECT COUNT(*) FROM ae_i_inv_e WHERE ( (ae_i_inv_e.part = '101682') AND (ae_i_inv_e.multitenant_id = 1) );

SELECT ae_i_loc_e.multitenant_id, ae_i_loc_e.warehouse, ae_i_loc_e.bin_location, ae_i_loc_e.inv_maxlev, ae_i_loc_e.jan_tl, ae_i_loc_e.jul_rop, ae_i_loc_e.sep_roa, ae_i_loc_e.nov_roa, ae_i_loc_e.link_tranx_num, ae_i_loc_e.nov_tl, ae_i_loc_e.apr_rop, ae_i_loc_e.inv_minlev, ae_i_loc_e.edit_date, ae_i_loc_e.jun_rop, ae_i_loc_e.mar_tl, ae_i_loc_e.jan_rop, ae_i_loc_e.qty, ae_i_loc_e.active, ae_i_loc_e.aug_rop, ae_i_loc_e.oct_roa, ae_i_loc_e.reorder_qty, ae_i_loc_e.sched_freq, ae_i_loc_e.jun_tl, ae_i_loc_e.aug_tl, ae_i_loc_e.feb_rop, ae_i_loc_e.parent_bin, ae_i_loc_e.bin_order, ae_i_loc_e.jul_tl, ae_i_loc_e.mar_rop, ae_i_loc_e.feb_tl, ae_i_loc_e.may_rop, ae_i_loc_e.part, ae_i_loc_e.sep_tl, ae_i_loc_e.apr_roa, ae_i_loc_e.parent_warehouse, ae_i_loc_e.mar_roa, ae_i_loc_e.start_date, ae_i_loc_e.aug_roa, ae_i_loc_e.edit_clerk, ae_i_loc_e.jun_roa, ae_i_loc_e.dec_rop, ae_i_loc_e.dec_tl, ae_i_loc_e.description, ae_i_loc_e.oct_rop, ae_i_loc_e.feb_roa, ae_i_loc_e.may_roa, ae_i_loc_e.jan_roa, ae_i_loc_e.may_tl, ae_i_loc_e.target_level, ae_i_loc_e.reorder_level, ae_i_loc_e.dec_roa, ae_i_loc_e.apr_tl, ae_i_loc_e.oct_tl, ae_i_loc_e.jul_roa, ae_i_loc_e.nov_rop, ae_i_loc_e.sep_rop FROM ae_i_loc_e WHERE ( (ae_i_loc_e.warehouse = 'M2350') AND (ae_i_loc_e.bin_location = 'UNIT1.B.2.2') AND (ae_i_loc_e.part = '101682') AND (ae_i_loc_e.multitenant_id = 1) ) ORDER BY ae_i_loc_e.multitenant_id, ae_i_loc_e.warehouse, ae_i_loc_e.bin_location;

SELECT ae_trigger.multitenant_id, ae_trigger.tranx_num, ae_trigger.doc_id, ae_trigger.filter_table_name, ae_trigger.seq, ae_trigger.type, ae_trigger.edit_clerk, ae_trigger.schd_freq, ae_trigger.status_code, ae_trigger.description, ae_trigger.schd_next_date, ae_trigger.edit_date, ae_trigger.active, ae_trigger.instance_id FROM ae_trigger WHERE ( (ae_trigger.type = 'INSERT') AND (ae_trigger.filter_table_name = 'AE_I_TRANS_REG') AND (ae_trigger.active = 'Y') AND (ae_trigger.multitenant_id = 1) ) ORDER BY ae_trigger.multitenant_id, ae_trigger.tranx_num;

INSERT INTO ae_i_trans_reg (multitenant_id, trans_num, source_screenname, source_tranx_no, source_tranx_item, warehouse, bin_location, part, inv_cost, bin_qty, trans_qty, dollar_adj, entry_clerk, entry_date, edit_clerk, edit_date, description, vend_cost, issue_factor, eqp_tag_id, asset_tag, sub_line_seq) VALUES (1, 241881, 'INVENTORY ADJUSTMENT', 25961, 0, 'M2350', 'UNIT1.B.2.2', '101682', 54.08, null, 2, 0, 'ETRISKA', '2016-07-19 09:00:24', 'ETRISKA', '2016-07-19 09:00:24', 'INVENTORY PRICE ADJUSTEMENT', null, null, null, null, 0);

SELECT ae_i_inv_e.multitenant_id, ae_i_inv_e.comm_code, ae_i_inv_e.cycle_code, ae_i_inv_e.edit_date, ae_i_inv_e.inv_class, ae_i_inv_e.description, ae_i_inv_e.inv_uom, ae_i_inv_e.item_type, ae_i_inv_e.manufacture_code, ae_i_inv_e.model, ae_i_inv_e.part, ae_i_inv_e.edit_clerk, ae_i_inv_e.active, ae_i_inv_e.fraction_yn, ae_i_inv_e.inv_item, ae_i_inv_e.pmi_basic, ae_i_inv_e.long_desc, ae_i_inv_e.link_tranx_num, ae_i_inv_e.doc_id, ae_i_inv_e.msds_num, ae_i_inv_e.msds_required, ae_i_inv_e.green_yn FROM ae_i_inv_e WHERE ( (ae_i_inv_e.multitenant_id = 1) AND (ae_i_inv_e.part = '101682') AND (ae_i_inv_e.multitenant_id = 1) );

SELECT ae_i_inv_w.multitenant_id, ae_i_inv_w.part, ae_i_inv_w.warehouse, ae_i_inv_w.mark_up, ae_i_inv_w.markup_sub_code, ae_i_inv_w.edit_date, ae_i_inv_w.spec_cd_flag, ae_i_inv_w.whse_cost, ae_i_inv_w.markup_funding_code, ae_i_inv_w.edit_clerk, ae_i_inv_w.link_tranx_num FROM ae_i_inv_w WHERE ( (ae_i_inv_w.part = '101682') AND (ae_i_inv_w.warehouse = 'M2350') AND (ae_i_inv_w.multitenant_id = 1) ) ORDER BY ae_i_inv_w.multitenant_id, ae_i_inv_w.part, ae_i_inv_w.warehouse;

SELECT ae_i_loc_e.multitenant_id, ae_i_loc_e.warehouse, ae_i_loc_e.bin_location, ae_i_loc_e.description, ae_i_loc_e.part, ae_i_loc_e.qty, ae_i_loc_e.start_date, ae_i_loc_e.sched_freq, ae_i_loc_e.parent_bin, ae_i_loc_e.parent_warehouse, ae_i_loc_e.inv_minlev, ae_i_loc_e.inv_maxlev, ae_i_loc_e.reorder_level, ae_i_loc_e.bin_order, ae_i_loc_e.reorder_qty, ae_i_loc_e.edit_date, ae_i_loc_e.edit_clerk, ae_i_loc_e.jan_rop, ae_i_loc_e.feb_rop, ae_i_loc_e.mar_rop, ae_i_loc_e.apr_rop, ae_i_loc_e.may_rop, ae_i_loc_e.jun_rop, ae_i_loc_e.jul_rop, ae_i_loc_e.aug_rop, ae_i_loc_e.sep_rop, ae_i_loc_e.oct_rop, ae_i_loc_e.nov_rop, ae_i_loc_e.dec_rop, ae_i_loc_e.jan_roa, ae_i_loc_e.feb_roa, ae_i_loc_e.mar_roa, ae_i_loc_e.apr_roa, ae_i_loc_e.may_roa, ae_i_loc_e.jun_roa, ae_i_loc_e.jul_roa, ae_i_loc_e.aug_roa, ae_i_loc_e.sep_roa, ae_i_loc_e.oct_roa, ae_i_loc_e.nov_roa, ae_i_loc_e.dec_roa, ae_i_loc_e.link_tranx_num, ae_i_loc_e.active, ae_i_loc_e.target_level, ae_i_loc_e.jan_tl, ae_i_loc_e.feb_tl, ae_i_loc_e.mar_tl, ae_i_loc_e.apr_tl, ae_i_loc_e.may_tl, ae_i_loc_e.jun_tl, ae_i_loc_e.jul_tl, ae_i_loc_e.aug_tl, ae_i_loc_e.sep_tl, ae_i_loc_e.oct_tl, ae_i_loc_e.nov_tl, ae_i_loc_e.dec_tl FROM ae_i_loc_e WHERE ( (ae_i_loc_e.multitenant_id = 1) AND (ae_i_loc_e.warehouse = 'M2350') AND (ae_i_loc_e.bin_location = 'UNIT1.B.2.2') AND (ae_i_loc_e.multitenant_id = 1) );

SELECT ae_i_loc_e.multitenant_id, ae_i_loc_e.warehouse, ae_i_loc_e.bin_location, ae_i_loc_e.description, ae_i_loc_e.part, ae_i_loc_e.qty, ae_i_loc_e.start_date, ae_i_loc_e.sched_freq, ae_i_loc_e.parent_bin, ae_i_loc_e.parent_warehouse, ae_i_loc_e.inv_minlev, ae_i_loc_e.inv_maxlev, ae_i_loc_e.reorder_level, ae_i_loc_e.bin_order, ae_i_loc_e.reorder_qty, ae_i_loc_e.edit_date, ae_i_loc_e.edit_clerk, ae_i_loc_e.jan_rop, ae_i_loc_e.feb_rop, ae_i_loc_e.mar_rop, ae_i_loc_e.apr_rop, ae_i_loc_e.may_rop, ae_i_loc_e.jun_rop, ae_i_loc_e.jul_rop, ae_i_loc_e.aug_rop, ae_i_loc_e.sep_rop, ae_i_loc_e.oct_rop, ae_i_loc_e.nov_rop, ae_i_loc_e.dec_rop, ae_i_loc_e.jan_roa, ae_i_loc_e.feb_roa, ae_i_loc_e.mar_roa, ae_i_loc_e.apr_roa, ae_i_loc_e.may_roa, ae_i_loc_e.jun_roa, ae_i_loc_e.jul_roa, ae_i_loc_e.aug_roa, ae_i_loc_e.sep_roa, ae_i_loc_e.oct_roa, ae_i_loc_e.nov_roa, ae_i_loc_e.dec_roa, ae_i_loc_e.link_tranx_num, ae_i_loc_e.active, ae_i_loc_e.target_level, ae_i_loc_e.jan_tl, ae_i_loc_e.feb_tl, ae_i_loc_e.mar_tl, ae_i_loc_e.apr_tl, ae_i_loc_e.may_tl, ae_i_loc_e.jun_tl, ae_i_loc_e.jul_tl, ae_i_loc_e.aug_tl, ae_i_loc_e.sep_tl, ae_i_loc_e.oct_tl, ae_i_loc_e.nov_tl, ae_i_loc_e.dec_tl FROM ae_i_loc_e WHERE ( (ae_i_loc_e.multitenant_id = 1) AND (ae_i_loc_e.warehouse = 'M2350') AND (ae_i_loc_e.bin_location = 'UNIT1.B.2.2') AND (ae_i_loc_e.multitenant_id = 1) );

UPDATE ae_i_loc_e SET qty = 2 WHERE ( (ae_i_loc_e.multitenant_id = 1) AND (ae_i_loc_e.warehouse = 'M2350') AND (ae_i_loc_e.bin_location = 'UNIT1.B.2.2') AND (ae_i_loc_e.multitenant_id = 1) );

SELECT ae_trigger.multitenant_id, ae_trigger.tranx_num, ae_trigger.doc_id, ae_trigger.filter_table_name, ae_trigger.seq, ae_trigger.type, ae_trigger.edit_clerk, ae_trigger.schd_freq, ae_trigger.status_code, ae_trigger.description, ae_trigger.schd_next_date, ae_trigger.edit_date, ae_trigger.active, ae_trigger.instance_id FROM ae_trigger WHERE ( (ae_trigger.type = 'UPDATE') AND (ae_trigger.filter_table_name = 'AE_I_LOC_E') AND (ae_trigger.active = 'Y') AND (ae_trigger.multitenant_id = 1) ) ORDER BY ae_trigger.multitenant_id, ae_trigger.tranx_num;

SELECT ae_i_inv_e.multitenant_id, ae_i_inv_e.comm_code, ae_i_inv_e.cycle_code, ae_i_inv_e.edit_date, ae_i_inv_e.inv_class, ae_i_inv_e.description, ae_i_inv_e.inv_uom, ae_i_inv_e.item_type, ae_i_inv_e.manufacture_code, ae_i_inv_e.model, ae_i_inv_e.part, ae_i_inv_e.edit_clerk, ae_i_inv_e.active, ae_i_inv_e.fraction_yn, ae_i_inv_e.inv_item, ae_i_inv_e.pmi_basic, ae_i_inv_e.long_desc, ae_i_inv_e.link_tranx_num, ae_i_inv_e.doc_id, ae_i_inv_e.msds_num, ae_i_inv_e.msds_required, ae_i_inv_e.green_yn FROM ae_i_inv_e WHERE ( (ae_i_inv_e.multitenant_id = 1) AND (ae_i_inv_e.part = '101682') AND (ae_i_inv_e.multitenant_id = 1) );

SELECT ae_i_inv_w.multitenant_id, ae_i_inv_w.part, ae_i_inv_w.warehouse, ae_i_inv_w.spec_cd_flag, ae_i_inv_w.mark_up, ae_i_inv_w.markup_funding_code, ae_i_inv_w.whse_cost, ae_i_inv_w.markup_sub_code, ae_i_inv_w.edit_date, ae_i_inv_w.edit_clerk, ae_i_inv_w.link_tranx_num FROM ae_i_inv_w WHERE ( (ae_i_inv_w.multitenant_id = 1) AND (ae_i_inv_w.part = '101682') AND (ae_i_inv_w.warehouse = 'M2350') AND (ae_i_inv_w.multitenant_id = 1) );

UPDATE ae_i_inv_w SET whse_cost = 54.0800 WHERE ( (ae_i_inv_w.multitenant_id = 1) AND (ae_i_inv_w.part = '101682') AND (ae_i_inv_w.warehouse = 'M2350') AND (ae_i_inv_w.multitenant_id = 1) );

SELECT ae_trigger.multitenant_id, ae_trigger.tranx_num, ae_trigger.doc_id, ae_trigger.filter_table_name, ae_trigger.seq, ae_trigger.type, ae_trigger.edit_clerk, ae_trigger.schd_freq, ae_trigger.status_code, ae_trigger.description, ae_trigger.schd_next_date, ae_trigger.edit_date, ae_trigger.active, ae_trigger.instance_id FROM ae_trigger WHERE ( (ae_trigger.type = 'UPDATE') AND (ae_trigger.filter_table_name = 'AE_I_INV_W') AND (ae_trigger.active = 'Y') AND (ae_trigger.multitenant_id = 1) ) ORDER BY ae_trigger.multitenant_id, ae_trigger.tranx_num;

SELECT ae_i_loc_e.multitenant_id, ae_i_loc_e.warehouse, ae_i_loc_e.bin_location, ae_i_loc_e.inv_maxlev, ae_i_loc_e.jan_tl, ae_i_loc_e.jul_rop, ae_i_loc_e.sep_roa, ae_i_loc_e.nov_roa, ae_i_loc_e.link_tranx_num, ae_i_loc_e.nov_tl, ae_i_loc_e.apr_rop, ae_i_loc_e.inv_minlev, ae_i_loc_e.edit_date, ae_i_loc_e.jun_rop, ae_i_loc_e.mar_tl, ae_i_loc_e.jan_rop, ae_i_loc_e.qty, ae_i_loc_e.active, ae_i_loc_e.aug_rop, ae_i_loc_e.oct_roa, ae_i_loc_e.reorder_qty, ae_i_loc_e.sched_freq, ae_i_loc_e.jun_tl, ae_i_loc_e.aug_tl, ae_i_loc_e.feb_rop, ae_i_loc_e.parent_bin, ae_i_loc_e.bin_order, ae_i_loc_e.jul_tl, ae_i_loc_e.mar_rop, ae_i_loc_e.feb_tl, ae_i_loc_e.may_rop, ae_i_loc_e.part, ae_i_loc_e.sep_tl, ae_i_loc_e.apr_roa, ae_i_loc_e.parent_warehouse, ae_i_loc_e.mar_roa, ae_i_loc_e.start_date, ae_i_loc_e.aug_roa, ae_i_loc_e.edit_clerk, ae_i_loc_e.jun_roa, ae_i_loc_e.dec_rop, ae_i_loc_e.dec_tl, ae_i_loc_e.description, ae_i_loc_e.oct_rop, ae_i_loc_e.feb_roa, ae_i_loc_e.may_roa, ae_i_loc_e.jan_roa, ae_i_loc_e.may_tl, ae_i_loc_e.target_level, ae_i_loc_e.reorder_level, ae_i_loc_e.dec_roa, ae_i_loc_e.apr_tl, ae_i_loc_e.oct_tl, ae_i_loc_e.jul_roa, ae_i_loc_e.nov_rop, ae_i_loc_e.sep_rop FROM ae_i_loc_e WHERE ( (ae_i_loc_e.warehouse = 'M2350') AND (ae_i_loc_e.part = '101682') AND (ae_i_loc_e.multitenant_id = 1) ) ORDER BY ae_i_loc_e.multitenant_id, ae_i_loc_e.warehouse, ae_i_loc_e.bin_location;

SELECT ae_i_inv_w.multitenant_id, ae_i_inv_w.part, ae_i_inv_w.warehouse, ae_i_inv_w.mark_up, ae_i_inv_w.markup_sub_code, ae_i_inv_w.edit_date, ae_i_inv_w.spec_cd_flag, ae_i_inv_w.whse_cost, ae_i_inv_w.markup_funding_code, ae_i_inv_w.edit_clerk, ae_i_inv_w.link_tranx_num FROM ae_i_inv_w WHERE ( (ae_i_inv_w.part = '101682') AND (ae_i_inv_w.warehouse = 'M2350') AND (ae_i_inv_w.multitenant_id = 1) ) ORDER BY ae_i_inv_w.multitenant_id, ae_i_inv_w.part, ae_i_inv_w.warehouse;

SELECT ae_external_url.multitenant_id, ae_external_url.screen_name, ae_external_url.url_id, ae_external_url.custom001_label, ae_external_url.custom001_field, ae_external_url.custom002_label, ae_external_url.custom002_field, ae_external_url.custom003_label, ae_external_url.custom003_field, ae_external_url.custom004_label, ae_external_url.custom004_field, ae_external_url.custom005_label, ae_external_url.custom005_field, ae_external_url.edit_date, ae_external_url.edit_clerk FROM ae_external_url WHERE ( (ae_external_url.multitenant_id = 1) AND (ae_external_url.screen_name = 'INV_ADJ_VIEW') AND (ae_external_url.multitenant_id = 1) );

SELECT ae_help.multitenant_id, ae_help.id, ae_help.sort_order, ae_help.edit_clerk, ae_help.edit_date, ae_help.description, ae_help.license, ae_help.title, ae_help.doc_id FROM ae_help WHERE ( (ae_help.license = 'OM') AND (ae_help.multitenant_id = 1) ) ORDER BY ae_help.multitenant_id, ae_help.id;

SELECT ae_document_version_series.multitenant_id, ae_document_version_series.doc_id, ae_document_version_series.doc_state, ae_document_version_series.doc_name, ae_document_version_series.long_desc, ae_document_version_series.created_at, ae_document_version_series.created_by, ae_document_version_series.checked_out_by, ae_document_version_series.type_id, ae_document_version_series.external_id, ae_document_version_series.version_yn, ae_document_version_series.fire_cloud_yn, ae_document_version_series.fire_cloud_id, ae_document_version_series.edit_date, ae_document_version_series.edit_clerk FROM ae_document_version_series WHERE ( (ae_document_version_series.multitenant_id = 1) AND (ae_document_version_series.doc_id = 'A3B91D4D-FCA2-4A81-BE0D-CF708582A8AA') AND (ae_document_version_series.multitenant_id = 1) );

SELECT ae_document_relationship.multitenant_id, ae_document_relationship.relationship_id, ae_document_relationship.relationship_type, ae_document_relationship.target_doc_id, ae_document_relationship.edit_date, ae_document_relationship.source_doc_id, ae_document_relationship.edit_clerk FROM ae_document_relationship WHERE ( (ae_document_relationship.relationship_id = 'A3B91D4D-FCA2-4A81-BE0D-CF708582A8AA') AND (ae_document_relationship.multitenant_id = 1) ) ORDER BY ae_document_relationship.multitenant_id, ae_document_relationship.relationship_id;

SELECT ae_document_tag.multitenant_id, ae_document_tag.doc_id, ae_document_tag.tag_id, ae_document_tag.edit_date, ae_document_tag.edit_clerk FROM ae_document_tag WHERE ( (ae_document_tag.doc_id = 'A3B91D4D-FCA2-4A81-BE0D-CF708582A8AA') AND (ae_document_tag.multitenant_id = 1) ) ORDER BY ae_document_tag.multitenant_id, ae_document_tag.doc_id, ae_document_tag.tag_id;

SELECT ae_document_version.edit_date, ae_document_version.checked_in_by, ae_document_version.mime_type, ae_document_version.content_id, ae_document_version.content_hash, ae_document_version.is_pwc, ae_document_version.doc_ver_id, ae_document_version.byte_length, ae_document_version.store_id, ae_document_version.doc_id, ae_document_version.repo_id, ae_document_version.edit_clerk, ae_document_version.checked_in_comment, ae_document_version.filename, ae_document_version.multitenant_id, ae_document_version.content_url, ae_document_version.version_label, ae_document_version.external_id FROM ae_document_version WHERE ( (ae_document_version.doc_id = 'A3B91D4D-FCA2-4A81-BE0D-CF708582A8AA') AND (ae_document_version.multitenant_id = 1) ) ORDER BY ae_document_version.edit_date;

SELECT ae_document_version.multitenant_id, ae_document_version.doc_id, ae_document_version.doc_ver_id, ae_document_version.content_id, ae_document_version.version_label, ae_document_version.is_pwc, ae_document_version.byte_length, ae_document_version.content_hash, ae_document_version.content_url, ae_document_version.repo_id, ae_document_version.checked_in_by, ae_document_version.checked_in_comment, ae_document_version.mime_type, ae_document_version.external_id, ae_document_version.store_id, ae_document_version.filename, ae_document_version.edit_date, ae_document_version.edit_clerk FROM ae_document_version WHERE ( (ae_document_version.multitenant_id = 1) AND (ae_document_version.doc_id = 'A3B91D4D-FCA2-4A81-BE0D-CF708582A8AA') AND (ae_document_version.doc_ver_id = '3652FBF8-5422-412B-8369-AA66F81260B6') AND (ae_document_version.multitenant_id = 1) );

SELECT ae_document_property.multitenant_id, ae_document_property.doc_id, ae_document_property.type_id, ae_document_property.type_prop_id, ae_document_property.seq, ae_document_property.edit_clerk, ae_document_property.edit_date, ae_document_property.prop_value FROM ae_document_property WHERE ( (ae_document_property.doc_id = 'A3B91D4D-FCA2-4A81-BE0D-CF708582A8AA') AND (ae_document_property.multitenant_id = 1) ) ORDER BY ae_document_property.multitenant_id, ae_document_property.doc_id, ae_document_property.type_id, ae_document_property.type_prop_id;

SELECT ae_document_property.multitenant_id, ae_document_property.doc_id, ae_document_property.type_id, ae_document_property.type_prop_id, ae_document_property.seq, ae_document_property.prop_value, ae_document_property.edit_date, ae_document_property.edit_clerk FROM ae_document_property WHERE ( (ae_document_property.multitenant_id = 1) AND (ae_document_property.doc_id = 'A3B91D4D-FCA2-4A81-BE0D-CF708582A8AA') AND (ae_document_property.type_id = 12) AND (ae_document_property.type_prop_id = 0) AND (ae_document_property.multitenant_id = 1) );

SELECT ae_document_property.multitenant_id, ae_document_property.doc_id, ae_document_property.type_id, ae_document_property.type_prop_id, ae_document_property.seq, ae_document_property.prop_value, ae_document_property.edit_date, ae_document_property.edit_clerk FROM ae_document_property WHERE ( (ae_document_property.multitenant_id = 1) AND (ae_document_property.doc_id = 'A3B91D4D-FCA2-4A81-BE0D-CF708582A8AA') AND (ae_document_property.type_id = 12) AND (ae_document_property.type_prop_id = 1) AND (ae_document_property.multitenant_id = 1) );

SELECT ae_document_property.multitenant_id, ae_document_property.doc_id, ae_document_property.type_id, ae_document_property.type_prop_id, ae_document_property.seq, ae_document_property.prop_value, ae_document_property.edit_date, ae_document_property.edit_clerk FROM ae_document_property WHERE ( (ae_document_property.multitenant_id = 1) AND (ae_document_property.doc_id = 'A3B91D4D-FCA2-4A81-BE0D-CF708582A8AA') AND (ae_document_property.type_id = 12) AND (ae_document_property.type_prop_id = 2) AND (ae_document_property.multitenant_id = 1) );

SELECT ae_document_property.multitenant_id, ae_document_property.doc_id, ae_document_property.type_id, ae_document_property.type_prop_id, ae_document_property.seq, ae_document_property.prop_value, ae_document_property.edit_date, ae_document_property.edit_clerk FROM ae_document_property WHERE ( (ae_document_property.multitenant_id = 1) AND (ae_document_property.doc_id = 'A3B91D4D-FCA2-4A81-BE0D-CF708582A8AA') AND (ae_document_property.type_id = 12) AND (ae_document_property.type_prop_id = 3) AND (ae_document_property.multitenant_id = 1) );

SELECT ae_document_property.multitenant_id, ae_document_property.doc_id, ae_document_property.type_id, ae_document_property.type_prop_id, ae_document_property.seq, ae_document_property.prop_value, ae_document_property.edit_date, ae_document_property.edit_clerk FROM ae_document_property WHERE ( (ae_document_property.multitenant_id = 1) AND (ae_document_property.doc_id = 'A3B91D4D-FCA2-4A81-BE0D-CF708582A8AA') AND (ae_document_property.type_id = 12) AND (ae_document_property.type_prop_id = 4) AND (ae_document_property.multitenant_id = 1) );

SELECT ae_document_ace.multitenant_id, ae_document_ace.doc_id, ae_document_ace.ace_id, ae_document_ace.perm_write, ae_document_ace.perm_read, ae_document_ace.role_id, ae_document_ace.edit_date, ae_document_ace.edit_clerk FROM ae_document_ace WHERE ( (ae_document_ace.doc_id = 'A3B91D4D-FCA2-4A81-BE0D-CF708582A8AA') AND (ae_document_ace.multitenant_id = 1) ) ORDER BY ae_document_ace.multitenant_id, ae_document_ace.doc_id, ae_document_ace.ace_id;

SELECT ae_artifact_link.multitenant_id, ae_artifact_link.doc_id, ae_artifact_link.link_tranx_num, ae_artifact_link.edit_date, ae_artifact_link.edit_clerk, ae_artifact_link.type_id FROM ae_artifact_link WHERE ( (ae_artifact_link.doc_id = 'A3B91D4D-FCA2-4A81-BE0D-CF708582A8AA') AND (ae_artifact_link.multitenant_id = 1) ) ORDER BY ae_artifact_link.multitenant_id, ae_artifact_link.doc_id, ae_artifact_link.link_tranx_num;

SELECT ae_document_state_hist.edit_date, ae_document_state_hist.edit_clerk, ae_document_state_hist.multitenant_id, ae_document_state_hist.doc_state, ae_document_state_hist.doc_id, ae_document_state_hist.seq FROM ae_document_state_hist WHERE ( (ae_document_state_hist.doc_id = 'A3B91D4D-FCA2-4A81-BE0D-CF708582A8AA') AND (ae_document_state_hist.multitenant_id = 1) ) ORDER BY ae_document_state_hist.edit_date DESC;

SELECT ae_document_version.multitenant_id, ae_document_version.doc_id, ae_document_version.doc_ver_id, ae_document_version.content_id, ae_document_version.version_label, ae_document_version.is_pwc, ae_document_version.byte_length, ae_document_version.content_hash, ae_document_version.content_url, ae_document_version.repo_id, ae_document_version.checked_in_by, ae_document_version.checked_in_comment, ae_document_version.mime_type, ae_document_version.external_id, ae_document_version.store_id, ae_document_version.filename, ae_document_version.edit_date, ae_document_version.edit_clerk FROM ae_document_version WHERE ( (ae_document_version.multitenant_id = 1) AND (ae_document_version.doc_id = 'A3B91D4D-FCA2-4A81-BE0D-CF708582A8AA') AND (ae_document_version.doc_ver_id = '3652FBF8-5422-412B-8369-AA66F81260B6') AND (ae_document_version.multitenant_id = 1) );

SELECT ae_s_sec_c.multitenant_id, ae_s_sec_c.login, ae_s_sec_c.assigned_by, ae_s_sec_c.assign_date, ae_s_sec_c.description, ae_s_sec_c.password, ae_s_sec_c.order_type, ae_s_sec_c.category, ae_s_sec_c.region_code, ae_s_sec_c.fac_id, ae_s_sec_c.bldg, ae_s_sec_c.labor_class, ae_s_sec_c.shop, ae_s_sec_c.company_id, ae_s_sec_c.dept_id, ae_s_sec_c.oc_code, ae_s_sec_c.requestor, ae_s_sec_c.passwd_exp_days, ae_s_sec_c.passwd_last_change, ae_s_sec_c.contractor, ae_s_sec_c.crt_flag, ae_s_sec_c.warehouse, ae_s_sec_c.employee_id, ae_s_sec_c.mfm_download, ae_s_sec_c.edit_date, ae_s_sec_c.edit_clerk, ae_s_sec_c.default_org, ae_s_sec_c.loc_id, ae_s_sec_c.location_code, ae_s_sec_c.active, ae_s_sec_c.link_tranx_num, ae_s_sec_c.last_login, ae_s_sec_c.admin_id, ae_s_sec_c.email, ae_s_sec_c.authorizer, ae_s_sec_c.authorizer_email, ae_s_sec_c.login_attempt_count, ae_s_sec_c.rpd_flag, ae_s_sec_c.ssha_hash, ae_s_sec_c.salt, ae_s_sec_c.acessibility_flag, ae_s_sec_c.fire_bucket FROM ae_s_sec_c WHERE ( (ae_s_sec_c.multitenant_id = 1) AND (ae_s_sec_c.login = 'ETRISKA') AND (ae_s_sec_c.multitenant_id = 1) );

SELECT ae_h_emp_e.multitenant_id, ae_h_emp_e.shop_person, ae_h_emp_e.lname, ae_h_emp_e.fname, ae_h_emp_e.mi, ae_h_emp_e.user_id, ae_h_emp_e.emp_type, ae_h_emp_e.edit_date, ae_h_emp_e.edit_clerk, ae_h_emp_e.labor_class, ae_h_emp_e.time_type, ae_h_emp_e.active, ae_h_emp_e.link_tranx_num, ae_h_emp_e.doc_id FROM ae_h_emp_e WHERE ( (ae_h_emp_e.multitenant_id = 1) AND (ae_h_emp_e.shop_person = '0038') AND (ae_h_emp_e.multitenant_id = 1) );

SELECT ae_i_whs_e.multitenant_id, ae_i_whs_e.warehouse, ae_i_whs_e.description, ae_i_whs_e.addr1, ae_i_whs_e.addr2, ae_i_whs_e.contact, ae_i_whs_e.region_code, ae_i_whs_e.fac_id, ae_i_whs_e.bldg, ae_i_whs_e.location_code, ae_i_whs_e.loc_id, ae_i_whs_e.city, ae_i_whs_e.state, ae_i_whs_e.zip_code, ae_i_whs_e.phone, ae_i_whs_e.fax, ae_i_whs_e.disable_validate, ae_i_whs_e.disable_whse_validation, ae_i_whs_e.edit_date, ae_i_whs_e.edit_clerk, ae_i_whs_e.company_id, ae_i_whs_e.dept_id, ae_i_whs_e.oc_code, ae_i_whs_e.mon_yn, ae_i_whs_e.tue_yn, ae_i_whs_e.wed_yn, ae_i_whs_e.thu_yn, ae_i_whs_e.fri_yn, ae_i_whs_e.sat_yn, ae_i_whs_e.sun_yn, ae_i_whs_e.offsetfunding_code, ae_i_whs_e.offsetsub_code, ae_i_whs_e.active, ae_i_whs_e.link_tranx_num, ae_i_whs_e.af1, ae_i_whs_e.af2, ae_i_whs_e.af3, ae_i_whs_e.af4, ae_i_whs_e.af5, ae_i_whs_e.af6, ae_i_whs_e.af7, ae_i_whs_e.af8, ae_i_whs_e.af9, ae_i_whs_e.af10, ae_i_whs_e.af11, ae_i_whs_e.af12, ae_i_whs_e.af13, ae_i_whs_e.af14, ae_i_whs_e.af15, ae_i_whs_e.af16, ae_i_whs_e.validate_stage, ae_i_whs_e.validate_staging_area_yn, ae_i_whs_e.validate_shop, ae_i_whs_e.locked_offset_dist FROM ae_i_whs_e WHERE ( (ae_i_whs_e.multitenant_id = 1) AND (ae_i_whs_e.warehouse = 'M2350') AND (ae_i_whs_e.multitenant_id = 1) );

SELECT ae_i_inv_e.multitenant_id, ae_i_inv_e.comm_code, ae_i_inv_e.cycle_code, ae_i_inv_e.edit_date, ae_i_inv_e.inv_class, ae_i_inv_e.description, ae_i_inv_e.inv_uom, ae_i_inv_e.item_type, ae_i_inv_e.manufacture_code, ae_i_inv_e.model, ae_i_inv_e.part, ae_i_inv_e.edit_clerk, ae_i_inv_e.active, ae_i_inv_e.fraction_yn, ae_i_inv_e.inv_item, ae_i_inv_e.pmi_basic, ae_i_inv_e.long_desc, ae_i_inv_e.link_tranx_num, ae_i_inv_e.doc_id, ae_i_inv_e.msds_num, ae_i_inv_e.msds_required, ae_i_inv_e.green_yn FROM ae_i_inv_e WHERE ( (ae_i_inv_e.multitenant_id = 1) AND (ae_i_inv_e.part = '101682') AND (ae_i_inv_e.multitenant_id = 1) );

