INSERT INTO AE_S_BLD_C (REGION_CODE, FAC_ID, BLDG, DESCRIPTION, BLDG_STATUS, PROP_TYPE, ADDR1, BLDG_CITY, 
BLDG_STATE_CODE, BLDG_ZIP,  USER_NONASSIGNABLE_SQFT, USER_GROSS, USER_ASSIGNABLE, SMART_BLDG, REDUNDANT, CABLE_VAULT, STANDBY_POWER, edit_clerk, edit_date)
SELECT (SELECT REGION_CODE FROM RVIEW_REGION_CONV WHERE V.BLDCITY = RVIEW_REGION_CONV.BLDCITY)REGION_CODE, 
BLDCAMPUSCDDESCRSHORT, BLDRECNBR, BLDDESCR50, BLDPHASE, BLDTYP, ADDR1, BLDCITY, BLDSTATE, BLDPOSTAL,
NONASSIGNEDSQRFT, TO_NUMBER(BLDGRSSSQRFT), ASSIGNEDSQRFT, 'N', 'N', 'N', 'N', 'ETRISKA', sysdate
FROM TMP_PROPERTIES_2 V;
INSERT INTO AE_S_BLD_H (REGION_CODE, FAC_ID, BLDG, BLDG_STATUS,EDIT_CLERK, EDIT_DATE, STATUS_DATE, LOGIN)
SELECT (SELECT REGION_CODE FROM RVIEW_REGION_CONV WHERE V.BLDCITY = RVIEW_REGION_CONV.BLDCITY)REGION_CODE,
V.BLDCAMPUSCDDESCRSHORT, V.BLDRECNBR, V.BLDPHASE, 'ETRISKA', SYSDATE, SYSDATE, 'ETRISKA'
FROM TMP_PROPERTIES_2 V;