INSERT INTO AE_B_FAC_E (FAC_ID, REGION_CODE, DESCRIPTION, STATE_CODE, EDIT_DATE, EDIT_CLERK, ACTIVE) VALUES ('AANONCAMP', 'AA', 'ANN ARBOR NON CAMPUS', 'MI', SYSDATE, 'ETRISKA', 'Y');
INSERT INTO AE_B_FAC_E (FAC_ID, REGION_CODE, DESCRIPTION, STATE_CODE, EDIT_DATE, EDIT_CLERK, ACTIVE) VALUES ('CDCOUTCL', 'AA', 'UNKNOWN', 'MI', SYSDATE, 'ETRISKA', 'Y');
INSERT INTO AE_B_FAC_E (FAC_ID, REGION_CODE, DESCRIPTION, STATE_CODE, EDIT_DATE, EDIT_CLERK, ACTIVE) VALUES ('CENTCAMP', 'AA', 'CENTRAL CAMPUS', 'MI', SYSDATE, 'ETRISKA', 'Y');
INSERT INTO AE_B_FAC_E (FAC_ID, REGION_CODE, DESCRIPTION, STATE_CODE, EDIT_DATE, EDIT_CLERK, ACTIVE) VALUES ('EASCAMP', 'AA', 'EAST CAMPUS', 'MI', SYSDATE, 'ETRISKA', 'Y');
INSERT INTO AE_B_FAC_E (FAC_ID, REGION_CODE, DESCRIPTION, STATE_CODE, EDIT_DATE, EDIT_CLERK, ACTIVE) VALUES ('MEDCAMP', 'AA', 'MEDICAL CAMPUS', 'MI', SYSDATE, 'ETRISKA', 'Y');
INSERT INTO AE_B_FAC_E (FAC_ID, REGION_CODE, DESCRIPTION, STATE_CODE, EDIT_DATE, EDIT_CLERK, ACTIVE) VALUES ('MEDCAMPUMH', 'AA', 'MEDICAL CAMPUS UMH', 'MI', SYSDATE, 'ETRISKA', 'Y');
INSERT INTO AE_B_FAC_E (FAC_ID, REGION_CODE, DESCRIPTION, STATE_CODE, EDIT_DATE, EDIT_CLERK, ACTIVE) VALUES ('NORCAMP', 'AA', 'NORTH CAMPUS', 'MI', SYSDATE, 'ETRISKA', 'Y');
INSERT INTO AE_B_FAC_E (FAC_ID, REGION_CODE, DESCRIPTION, STATE_CODE, EDIT_DATE, EDIT_CLERK, ACTIVE) VALUES ('OTHER', 'AA', 'OTHER', 'MI', SYSDATE, 'ETRISKA', 'Y');
INSERT INTO AE_B_FAC_E (FAC_ID, REGION_CODE, DESCRIPTION, STATE_CODE, EDIT_DATE, EDIT_CLERK, ACTIVE) VALUES ('SOUCAMP', 'AA', 'SOUTH CAMPUS', 'MI', SYSDATE, 'ETRISKA', 'Y');

INSERT INTO AE_B_FAC_E (FAC_ID, REGION_CODE, DESCRIPTION, STATE_CODE, EDIT_DATE, EDIT_CLERK, ACTIVE) VALUES ('EASCAMP', 'AAT', 'EAST CAMPUS', 'MI', SYSDATE, 'ETRISKA', 'Y');
INSERT INTO AE_B_FAC_E (FAC_ID, REGION_CODE, DESCRIPTION, STATE_CODE, EDIT_DATE, EDIT_CLERK, ACTIVE) VALUES ('OTHER', 'AAT', 'OTHER', 'MI', SYSDATE, 'ETRISKA', 'Y');

INSERT INTO AE_B_FAC_E (FAC_ID, REGION_CODE, DESCRIPTION, STATE_CODE, EDIT_DATE, EDIT_CLERK, ACTIVE) VALUES ('OTHER', 'BV', 'OTHER', 'MI', SYSDATE, 'ETRISKA', 'Y');

INSERT INTO AE_B_FAC_E (FAC_ID, REGION_CODE, DESCRIPTION, STATE_CODE, EDIT_DATE, EDIT_CLERK, ACTIVE) VALUES ('CDCOUTCL', 'BH', 'UNKNOWN', 'MI', SYSDATE, 'ETRISKA', 'Y');

INSERT INTO AE_B_FAC_E (FAC_ID, REGION_CODE, DESCRIPTION, STATE_CODE, EDIT_DATE, EDIT_CLERK, ACTIVE) VALUES ('CDCOUTCL', 'BR', 'UNKNOWN', 'MI', SYSDATE, 'ETRISKA', 'Y');
INSERT INTO AE_B_FAC_E (FAC_ID, REGION_CODE, DESCRIPTION, STATE_CODE, EDIT_DATE, EDIT_CLERK, ACTIVE) VALUES ('OTHER', 'BR', 'OTHER', 'MI', SYSDATE, 'ETRISKA', 'Y');

INSERT INTO AE_B_FAC_E (FAC_ID, REGION_CODE, DESCRIPTION, STATE_CODE, EDIT_DATE, EDIT_CLERK, ACTIVE) VALUES ('CDCOUTCL', 'CN', 'UNKNOWN', 'MI', SYSDATE, 'ETRISKA', 'Y');

INSERT INTO AE_B_FAC_E (FAC_ID, REGION_CODE, DESCRIPTION, STATE_CODE, EDIT_DATE, EDIT_CLERK, ACTIVE) VALUES ('MEDCAMPUMH', 'CH', 'MEDICAL CAMPUS UMH', 'MI', SYSDATE, 'ETRISKA', 'Y');

INSERT INTO AE_B_FAC_E (FAC_ID, REGION_CODE, DESCRIPTION, STATE_CODE, EDIT_DATE, EDIT_CLERK, ACTIVE) VALUES ('OTHER', 'CC', 'OTHER', 'TX', SYSDATE, 'ETRISKA', 'Y');

INSERT INTO AE_B_FAC_E (FAC_ID, REGION_CODE, DESCRIPTION, STATE_CODE, EDIT_DATE, EDIT_CLERK, ACTIVE) VALUES ('OTHER', 'DB', 'OTHER', 'MI', SYSDATE, 'ETRISKA', 'Y');
INSERT INTO AE_B_FAC_E (FAC_ID, REGION_CODE, DESCRIPTION, STATE_CODE, EDIT_DATE, EDIT_CLERK, ACTIVE) VALUES ('UM_DEARB', 'DB', 'DEARBORN', 'MI', SYSDATE, 'ETRISKA', 'Y');
INSERT INTO AE_B_FAC_E (FAC_ID, REGION_CODE, DESCRIPTION, STATE_CODE, EDIT_DATE, EDIT_CLERK, ACTIVE) VALUES ('CDCOUTCL', 'DB', 'UNKNOWN', 'MI', SYSDATE, 'ETRISKA', 'Y');

INSERT INTO AE_B_FAC_E (FAC_ID, REGION_CODE, DESCRIPTION, STATE_CODE, EDIT_DATE, EDIT_CLERK, ACTIVE) VALUES ('OTHER', 'DT', 'OTHER', 'MI', SYSDATE, 'ETRISKA', 'Y');

INSERT INTO AE_B_FAC_E (FAC_ID, REGION_CODE, DESCRIPTION, STATE_CODE, EDIT_DATE, EDIT_CLERK, ACTIVE) VALUES ('OTHER', 'DX', 'OTHER', 'MI', SYSDATE, 'ETRISKA', 'Y');
INSERT INTO AE_B_FAC_E (FAC_ID, REGION_CODE, DESCRIPTION, STATE_CODE, EDIT_DATE, EDIT_CLERK, ACTIVE) VALUES ('CDCOUTCL', 'DX', 'UNKNOWN', 'MI', SYSDATE, 'ETRISKA', 'Y');

INSERT INTO AE_B_FAC_E (FAC_ID, REGION_CODE, DESCRIPTION, STATE_CODE, EDIT_DATE, EDIT_CLERK, ACTIVE) VALUES ('OTHER', 'DXT', 'OTHER', 'MI', SYSDATE, 'ETRISKA', 'Y');

INSERT INTO AE_B_FAC_E (FAC_ID, REGION_CODE, DESCRIPTION, STATE_CODE, EDIT_DATE, EDIT_CLERK, ACTIVE) VALUES ('OTHER', 'EL', 'OTHER', 'MI', SYSDATE, 'ETRISKA', 'Y');
INSERT INTO AE_B_FAC_E (FAC_ID, REGION_CODE, DESCRIPTION, STATE_CODE, EDIT_DATE, EDIT_CLERK, ACTIVE) VALUES ('CDCOUTCL', 'EL', 'UNKNOWN', 'MI', SYSDATE, 'ETRISKA', 'Y');

INSERT INTO AE_B_FAC_E (FAC_ID, REGION_CODE, DESCRIPTION, STATE_CODE, EDIT_DATE, EDIT_CLERK, ACTIVE) VALUES ('OTHER', 'FR', 'OTHER', 'MI', SYSDATE, 'ETRISKA', 'Y');

INSERT INTO AE_B_FAC_E (FAC_ID, REGION_CODE, DESCRIPTION, STATE_CODE, EDIT_DATE, EDIT_CLERK, ACTIVE) VALUES ('UM-FLINT', 'FL', 'FLINT', 'MI', SYSDATE, 'ETRISKA', 'Y');

INSERT INTO AE_B_FAC_E (FAC_ID, REGION_CODE, DESCRIPTION, STATE_CODE, EDIT_DATE, EDIT_CLERK, ACTIVE) VALUES ('OTHER', 'FP', 'OTHER', 'IL', SYSDATE, 'ETRISKA', 'Y');

INSERT INTO AE_B_FAC_E (FAC_ID, REGION_CODE, DESCRIPTION, STATE_CODE, EDIT_DATE, EDIT_CLERK, ACTIVE) VALUES ('OTHER', 'FV', 'OTHER', 'MI', SYSDATE, 'ETRISKA', 'Y');

INSERT INTO AE_B_FAC_E (FAC_ID, REGION_CODE, DESCRIPTION, STATE_CODE, EDIT_DATE, EDIT_CLERK, ACTIVE) VALUES ('UM-FLINT', 'GR', 'FLINT', 'MI', SYSDATE, 'ETRISKA', 'Y');

INSERT INTO AE_B_FAC_E (FAC_ID, REGION_CODE, DESCRIPTION, STATE_CODE, EDIT_DATE, EDIT_CLERK, ACTIVE) VALUES ('OTHER', 'HP', 'OTHER', 'MI', SYSDATE, 'ETRISKA', 'Y');

INSERT INTO AE_B_FAC_E (FAC_ID, REGION_CODE, DESCRIPTION, STATE_CODE, EDIT_DATE, EDIT_CLERK, ACTIVE) VALUES ('CDCOUTCL', 'HW', 'UNKNOWN', 'MI', SYSDATE, 'ETRISKA', 'Y');

INSERT INTO AE_B_FAC_E (FAC_ID, REGION_CODE, DESCRIPTION, STATE_CODE, EDIT_DATE, EDIT_CLERK, ACTIVE) VALUES ('CDCOUTCL', 'JK', 'UNKNOWN', 'MI', SYSDATE, 'ETRISKA', 'Y');
INSERT INTO AE_B_FAC_E (FAC_ID, REGION_CODE, DESCRIPTION, STATE_CODE, EDIT_DATE, EDIT_CLERK, ACTIVE) VALUES ('OTHER', 'JK', 'OTHER', 'MI', SYSDATE, 'ETRISKA', 'Y');

INSERT INTO AE_B_FAC_E (FAC_ID, REGION_CODE, DESCRIPTION, STATE_CODE, EDIT_DATE, EDIT_CLERK, ACTIVE) VALUES ('CDCOUTCL', 'KM', 'UNKNOWN', 'MI', SYSDATE, 'ETRISKA', 'Y');
INSERT INTO AE_B_FAC_E (FAC_ID, REGION_CODE, DESCRIPTION, STATE_CODE, EDIT_DATE, EDIT_CLERK, ACTIVE) VALUES ('OTHER', 'KM', 'OTHER', 'MI', SYSDATE, 'ETRISKA', 'Y');

INSERT INTO AE_B_FAC_E (FAC_ID, REGION_CODE, DESCRIPTION, STATE_CODE, EDIT_DATE, EDIT_CLERK, ACTIVE) VALUES ('OTHER', 'LO', 'OTHER', 'MI', SYSDATE, 'ETRISKA', 'Y');

INSERT INTO AE_B_FAC_E (FAC_ID, REGION_CODE, DESCRIPTION, STATE_CODE, EDIT_DATE, EDIT_CLERK, ACTIVE) VALUES ('OTHER', 'LN', 'OTHER', 'MI', SYSDATE, 'ETRISKA', 'Y');

INSERT INTO AE_B_FAC_E (FAC_ID, REGION_CODE, DESCRIPTION, STATE_CODE, EDIT_DATE, EDIT_CLERK, ACTIVE) VALUES ('CDCOUTCL', 'LV', 'UNKNOWN', 'MI', SYSDATE, 'ETRISKA', 'Y');
INSERT INTO AE_B_FAC_E (FAC_ID, REGION_CODE, DESCRIPTION, STATE_CODE, EDIT_DATE, EDIT_CLERK, ACTIVE) VALUES ('OTHER', 'LV', 'OTHER', 'MI', SYSDATE, 'ETRISKA', 'Y');

INSERT INTO AE_B_FAC_E (FAC_ID, REGION_CODE, DESCRIPTION, STATE_CODE, EDIT_DATE, EDIT_CLERK, ACTIVE) VALUES ('CDCOUTCL', 'ML', 'UNKNOWN', 'MI', SYSDATE, 'ETRISKA', 'Y');
INSERT INTO AE_B_FAC_E (FAC_ID, REGION_CODE, DESCRIPTION, STATE_CODE, EDIT_DATE, EDIT_CLERK, ACTIVE) VALUES ('OTHER', 'ML', 'OTHER', 'MI', SYSDATE, 'ETRISKA', 'Y');

INSERT INTO AE_B_FAC_E (FAC_ID, REGION_CODE, DESCRIPTION, STATE_CODE, EDIT_DATE, EDIT_CLERK, ACTIVE) VALUES ('OTHER', 'NY', 'OTHER', 'NY', SYSDATE, 'ETRISKA', 'Y');

INSERT INTO AE_B_FAC_E (FAC_ID, REGION_CODE, DESCRIPTION, STATE_CODE, EDIT_DATE, EDIT_CLERK, ACTIVE) VALUES ('OTHER', 'PC', 'OTHER', 'FL', SYSDATE, 'ETRISKA', 'Y');

INSERT INTO AE_B_FAC_E (FAC_ID, REGION_CODE, DESCRIPTION, STATE_CODE, EDIT_DATE, EDIT_CLERK, ACTIVE) VALUES ('OTHER', 'PD', 'OTHER', 'CA', SYSDATE, 'ETRISKA', 'Y');

INSERT INTO AE_B_FAC_E (FAC_ID, REGION_CODE, DESCRIPTION, STATE_CODE, EDIT_DATE, EDIT_CLERK, ACTIVE) VALUES ('CAMPS', 'PS', 'CAMPS', 'MI', SYSDATE, 'ETRISKA', 'Y');

INSERT INTO AE_B_FAC_E (FAC_ID, REGION_CODE, DESCRIPTION, STATE_CODE, EDIT_DATE, EDIT_CLERK, ACTIVE) VALUES ('CAMPS', 'PN', 'CAMPS', 'MI', SYSDATE, 'ETRISKA', 'Y');

INSERT INTO AE_B_FAC_E (FAC_ID, REGION_CODE, DESCRIPTION, STATE_CODE, EDIT_DATE, EDIT_CLERK, ACTIVE) VALUES ('OTHER', 'PB', 'OTHER', 'PA', SYSDATE, 'ETRISKA', 'Y');

INSERT INTO AE_B_FAC_E (FAC_ID, REGION_CODE, DESCRIPTION, STATE_CODE, EDIT_DATE, EDIT_CLERK, ACTIVE) VALUES ('CDCOUTCL', 'PL', 'UNKNOWN', 'MI', SYSDATE, 'ETRISKA', 'Y');

INSERT INTO AE_B_FAC_E (FAC_ID, REGION_CODE, DESCRIPTION, STATE_CODE, EDIT_DATE, EDIT_CLERK, ACTIVE) VALUES ('OTHER', 'PN', 'OTHER', 'MI', SYSDATE, 'ETRISKA', 'Y');

INSERT INTO AE_B_FAC_E (FAC_ID, REGION_CODE, DESCRIPTION, STATE_CODE, EDIT_DATE, EDIT_CLERK, ACTIVE) VALUES ('CAMPS', 'PNT', 'CAMPS', 'MI', SYSDATE, 'ETRISKA', 'Y');

INSERT INTO AE_B_FAC_E (FAC_ID, REGION_CODE, DESCRIPTION, STATE_CODE, EDIT_DATE, EDIT_CLERK, ACTIVE) VALUES ('OTHER', 'RM', 'OTHER', 'MI', SYSDATE, 'ETRISKA', 'Y');

INSERT INTO AE_B_FAC_E (FAC_ID, REGION_CODE, DESCRIPTION, STATE_CODE, EDIT_DATE, EDIT_CLERK, ACTIVE) VALUES ('OTHER', 'ST', 'OTHER', 'IL', SYSDATE, 'ETRISKA', 'Y');

INSERT INTO AE_B_FAC_E (FAC_ID, REGION_CODE, DESCRIPTION, STATE_CODE, EDIT_DATE, EDIT_CLERK, ACTIVE) VALUES ('OTHER', 'SL', 'OTHER', 'MI', SYSDATE, 'ETRISKA', 'Y');
INSERT INTO AE_B_FAC_E (FAC_ID, REGION_CODE, DESCRIPTION, STATE_CODE, EDIT_DATE, EDIT_CLERK, ACTIVE) VALUES ('CDCOUTCL', 'SL', 'UNKNOWN', 'MI', SYSDATE, 'ETRISKA', 'Y');

INSERT INTO AE_B_FAC_E (FAC_ID, REGION_CODE, DESCRIPTION, STATE_CODE, EDIT_DATE, EDIT_CLERK, ACTIVE) VALUES ('CAMPS', 'STM', 'CAMPS', 'MI', SYSDATE, 'ETRISKA', 'Y');

INSERT INTO AE_B_FAC_E (FAC_ID, REGION_CODE, DESCRIPTION, STATE_CODE, EDIT_DATE, EDIT_CLERK, ACTIVE) VALUES ('CAMPS', 'SCT', 'CAMPS', 'MI', SYSDATE, 'ETRISKA', 'Y');

INSERT INTO AE_B_FAC_E (FAC_ID, REGION_CODE, DESCRIPTION, STATE_CODE, EDIT_DATE, EDIT_CLERK, ACTIVE) VALUES ('OTHER', 'SF', 'OTHER', 'MI', SYSDATE, 'ETRISKA', 'Y');

INSERT INTO AE_B_FAC_E (FAC_ID, REGION_CODE, DESCRIPTION, STATE_CODE, EDIT_DATE, EDIT_CLERK, ACTIVE) VALUES ('OTHER', 'SPT', 'OTHER', 'MI', SYSDATE, 'ETRISKA', 'Y');

INSERT INTO AE_B_FAC_E (FAC_ID, REGION_CODE, DESCRIPTION, STATE_CODE, EDIT_DATE, EDIT_CLERK, ACTIVE) VALUES ('OTHER', 'TL', 'OTHER', 'MI', SYSDATE, 'ETRISKA', 'Y');

INSERT INTO AE_B_FAC_E (FAC_ID, REGION_CODE, DESCRIPTION, STATE_CODE, EDIT_DATE, EDIT_CLERK, ACTIVE) VALUES ('OTHER', 'TM', 'OTHER', 'MI', SYSDATE, 'ETRISKA', 'Y');

INSERT INTO AE_B_FAC_E (FAC_ID, REGION_CODE, DESCRIPTION, STATE_CODE, EDIT_DATE, EDIT_CLERK, ACTIVE) VALUES ('OTHER', 'TC', 'OTHER', 'MI', SYSDATE, 'ETRISKA', 'Y');

INSERT INTO AE_B_FAC_E (FAC_ID, REGION_CODE, DESCRIPTION, STATE_CODE, EDIT_DATE, EDIT_CLERK, ACTIVE) VALUES ('OTHER', 'TS', 'OTHER', 'AZ', SYSDATE, 'ETRISKA', 'Y');

INSERT INTO AE_B_FAC_E (FAC_ID, REGION_CODE, DESCRIPTION, STATE_CODE, EDIT_DATE, EDIT_CLERK, ACTIVE) VALUES ('WILLORUN', 'VBT', 'WILLOW RUN', 'MI', SYSDATE, 'ETRISKA', 'Y');

INSERT INTO AE_B_FAC_E (FAC_ID, REGION_CODE, DESCRIPTION, STATE_CODE, EDIT_DATE, EDIT_CLERK, ACTIVE) VALUES ('OTHER', 'WR', 'OTHER', 'MI', SYSDATE, 'ETRISKA', 'Y');

INSERT INTO AE_B_FAC_E (FAC_ID, REGION_CODE, DESCRIPTION, STATE_CODE, EDIT_DATE, EDIT_CLERK, ACTIVE) VALUES ('OTHER', 'WA', 'OTHER', 'DC', SYSDATE, 'ETRISKA', 'Y');

INSERT INTO AE_B_FAC_E (FAC_ID, REGION_CODE, DESCRIPTION, STATE_CODE, EDIT_DATE, EDIT_CLERK, ACTIVE) VALUES ('OTHER', 'WL', 'OTHER', 'MI', SYSDATE, 'ETRISKA', 'Y');

INSERT INTO AE_B_FAC_E (FAC_ID, REGION_CODE, DESCRIPTION, STATE_CODE, EDIT_DATE, EDIT_CLERK, ACTIVE) VALUES ('OTHER', 'WBT', 'OTHER', 'MI', SYSDATE, 'ETRISKA', 'Y');

INSERT INTO AE_B_FAC_E (FAC_ID, REGION_CODE, DESCRIPTION, STATE_CODE, EDIT_DATE, EDIT_CLERK, ACTIVE) VALUES ('CDCOUTCL', 'WB', 'OTHER', 'MI', SYSDATE, 'ETRISKA', 'Y');

INSERT INTO AE_B_FAC_E (FAC_ID, REGION_CODE, DESCRIPTION, STATE_CODE, EDIT_DATE, EDIT_CLERK, ACTIVE) VALUES ('OTHER', 'WM', 'OTHER', 'MI', SYSDATE, 'ETRISKA', 'Y');

INSERT INTO AE_B_FAC_E (FAC_ID, REGION_CODE, DESCRIPTION, STATE_CODE, EDIT_DATE, EDIT_CLERK, ACTIVE) VALUES ('OTHER', 'YP', 'OTHER', 'MI', SYSDATE, 'ETRISKA', 'Y');
INSERT INTO AE_B_FAC_E (FAC_ID, REGION_CODE, DESCRIPTION, STATE_CODE, EDIT_DATE, EDIT_CLERK, ACTIVE) VALUES ('CDCOUTCL', 'YP', 'UNKNOWN', 'MI', SYSDATE, 'ETRISKA', 'Y');
COMMIT;