INSERT INTO AE_B_LOC_D (REGION_CODE, FAC_ID, BLDG, LOCATION_CODE, FLR_ID, LOC_ID, LOC_TYPE, LOC_STATUS, OC_CODE, COMPANY_ID, DEPT_ID, USER_GROSS, SPACE_TYPE, EDIT_CLERK, EDIT_DATE, ASSIGNMENT_ID)
SELECT (SELECT REGION_CODE FROM AE_S_BLD_C A WHERE A.BLDG = V.BLDG) REGION_CODE,
(SELECT FAC_ID FROM AE_S_BLD_C A WHERE A.BLDG = V.BLDG) FAC_ID,
V.BLDG, V.LOCATION_CODE, V.FLR_ID, V.LOCATION_CODE||'^1', V.LOC_TYPE, 'A', V.OC_CODE, V.COMPANY_ID, V.DEPT_ID, V.USER_GROSS, V.SPACE_TYPE, 'ETRISKA', SYSDATE, V.ASSIGNMENT_ID
from TMP_LOCATIONS v