CREATE TABLE TMP_EQM_E AS SELECT * FROM AE_R_EQM_E@FMS.UMICH;
CREATE TABLE TMP_EQM_GROUP AS SELECT * FROM AE_R_EQM_GROUP@FMS.UMICH;
CREATE TABLE TMP_EQM_S AS SELECT * FROM AE_R_EQM_S@FMS.UMICH;
CREATE TABLE TMP_ATTR AS SELECT * FROM AE_R_EQM_GROUP_ATTR@FMS.UMICH;
CREATE TABLE TMP_ATTR_VALUES AS SELECT * FROM AE_R_EQM_E_ATTR@FMS.UMICH;

UPDATE TMP_EQM_E A SET A.REGION_CODE = (SELECT REGION_CODE FROM AE_S_BLD_C B WHERE A.BLDG = B.BLDG),
 A.FAC_ID = (SELECT FAC_ID FROM AE_S_BLD_C B WHERE A.BLDG = B.BLDG);

INSERT INTO AE_A_ASSET_GROUP (ASSET_TYPE, ASSET_GROUP, DESCRIPTION, ACTIVE, EDIT_DATE, EDIT_CLERK, RENTABLE_YN)
SELECT 'SERIALIZED', EQM_GROUP, DESCRIPTION, 'Y', SYSDATE, 'ETRISKA', 'N'
FROM TMP_EQM_GROUP;

INSERT INTO AE_A_ASSET_E (ASSET_TAG, ASSET_TYPE, DESCRIPTION, REGION_CODE, FAC_ID, BLDG, EDIT_DATE, EDIT_CLERK, QTY, LONG_DESC, SHOP, SHOP_PERSON, ROUTE_NO, ROUTE_SEQ, STATUS_CODE,
  RENTABLE_YN, LOCKOUT, ASSET_GROUP, TAG_NUMBER, MANUFACTURE_CODE, MANU_PART_NUMBER, DISPOSAL_PERCENT)
SELECT EQP_TAG_ID, 'SERIALIZED', DESCRIPTION, REGION_CODE, FAC_ID, BLDG, SYSDATE, 'ETRISKA', 1, LONG_DESC, SHOP, SHOP_PERSON, ROUTE_NO, ROUTE_SEQ, 'ACTIVE', 'N', 'N', EQM_GROUP, EQP_TAG_ID, MANUFACTURE_CODE, MANU_PART_NUMBER, 0 
FROM TMP_EQM_E
WHERE EQM_STATUS IN ('IN USE', 'IN USE / REPLACEMENT')
AND LENGTH(EQP_TAG_ID) <=25;

INSERT INTO AE_A_AST_GRP_ATTR (ASSET_TYPE, ASSET_GROUP, ATTR_ID, LABEL, FIELD_TYPE, LENGTH, SEQUENCE, REQUIRED, ACTIVE_YN, EDIT_DATE, EDIT_CLERK, DESCRIPTION)
SELECT 'SERIALIZED', EQM_GROUP, ATTR_ID, LABEL, FIELD_TYPE, LENGTH, SEQUENCE, REQUIRED, 'Y', NVL(EDIT_DATE,SYSDATE), NVL(EDIT_CLERK,'ETRISKA'), NULL
FROM TMP_ATTR;

INSERT INTO AE_A_ASSET_ATTR (ASSET_TAG, ASSET_TYPE, ASSET_GROUP, ATTR_ID, ATTR_VALUE, EDIT_DATE, EDIT_CLERK, SEQUENCE)
SELECT EQP_TAG_ID, 'SERIALIZED', EQM_GROUP, ATTR_ID, ATTR_VALUE, NVL(EDIT_DATE, SYSDATE), NVL(EDIT_CLERK, 'ETRISKA'), SEQ
FROM TMP_ATTR_VALUES
WHERE LENGTH(EQP_TAG_ID) <=25;