CREATE INDEX "ROOT"."PAP_TC3_SWIPE_R_IDX$$_00E50000"
ON "ROOT"."PAP_TC3_SWIPE_RAW"
("ID","USED_SWIPE_DATE")
COMPUTE STATISTICS;

CREATE INDEX "ROOT"."AE_H_EMP_E_IDX$$_00E50001"
ON "ROOT"."AE_H_EMP_E"
("USER_ID","ACTIVE","MULTITENANT_ID","SHOP_PERSON")
COMPUTE STATISTICS;

CREATE INDEX "ROOT"."AE_S_DEP_E_IDX$$_00E50002"
ON "ROOT"."AE_S_DEP_E"
("DEPT_ID","MULTITENANT_ID")
COMPUTE STATISTICS;

CREATE INDEX "ROOT"."PAP_TC3_PUNCH_IDX$$_00E50003"
ON "ROOT"."PAP_TC3_PUNCH"
("UMID","ALTERED_USER_REVIEWED_DATE","ID")
COMPUTE STATISTICS;

CREATE INDEX "ROOT"."PAP_TC3_PUNCH_D_IDX$$_00E50004"
ON "ROOT"."PAP_TC3_PUNCH_DETAIL"
("PUNCH_ID","ISACTIVE")
COMPUTE STATISTICS;

CREATE INDEX "ROOT"."PAP_TC3_TIMECAR_IDX$$_00E50005"
ON "ROOT"."PAP_TC3_TIMECARD"
("PUNCH_ID","STATUS")
COMPUTE STATISTICS;

CREATE BITMAP INDEX "ROOT".
"AE_A_ASSET_E_IDX$$_00E50006"
ON "ROOT"."AE_A_ASSET_E"
("BLDG")
COMPUTE STATISTICS;

CREATE BITMAP INDEX "ROOT"."AE_A_ASSET_E_IDX$$_00E50007"
ON "ROOT"."AE_A_ASSET_E"
("FAC_ID")
COMPUTE STATISTICS;

CREATE BITMAP INDEX "ROOT"."AE_A_ASSET_E_IDX$$_00E50008"
ON "ROOT"."AE_A_ASSET_E"
("REGION_CODE")
COMPUTE STATISTICS;

CREATE INDEX "ROOT"."AE_A_ASSET_STAT_IDX$$_00E50009"
ON "ROOT"."AE_A_ASSET_STATUS"
("ACTIVE","MULTITENANT_ID","STATUS_CODE")
COMPUTE STATISTICS;

CREATE INDEX "ROOT"."AE_L_SHP_C_IDX$$_00E50013"
ON "ROOT"."AE_L_SHP_C"
("TIME_TYPE","SHOP","LABOR_CLASS","JOB_CLASS","MULTITENANT_ID")
COMPUTE STATISTICS;

CREATE INDEX "ROOT"."AE_P_PHS_E_IDX$$_00E50014"
ON "ROOT"."AE_P_PHS_E"
("CRAFT_CODE","MULTITENANT_ID","PROPOSAL")
COMPUTE STATISTICS;

CREATE INDEX "ROOT"."AE_P_PRO_E_IDX$$_00E50015"
ON "ROOT"."AE_P_PRO_E"
("MULTITENANT_ID","DESCRIPTION","PROPOSAL")
COMPUTE STATISTICS;

CREATE INDEX "ROOT"."AE_P_PRO_E_IDX$$_00E50016"
ON "ROOT"."AE_P_PRO_E"
("BLDG","MULTITENANT_ID","DESCRIPTION")
COMPUTE STATISTICS;

CREATE BITMAP INDEX "ROOT"."AE_P_PHS_E_IDX$$_00E50017"
ON "ROOT"."AE_P_PHS_E"
("SHOP")
COMPUTE STATISTICS;

CREATE INDEX "ROOT"."AE_S_FND_A_IDX$$_00E50018"
ON "ROOT"."AE_S_FND_A"
("TRANX_DATE")
COMPUTE STATISTICS;

CREATE INDEX "ROOT"."AE_S_FND_A_IDX$$_00E50019"
ON "ROOT"."AE_S_FND_A"
("TRANX_NO","MULTITENANT_ID")
COMPUTE STATISTICS;

CREATE INDEX "ROOT"."AE_S_FND_A_IDX$$_00E5001A"
ON "ROOT"."AE_S_FND_A"
("AMOUNT","EDIT_CLERK")
COMPUTE STATISTICS;

CREATE INDEX "ROOT"."AE_P_PHS_E_IDX$$_00E5001B"
ON "ROOT"."AE_P_PHS_E"
("MULTITENANT_ID","PROPOSAL")
COMPUTE STATISTICS;

CREATE INDEX "ROOT"."AE_P_PHS_E_IDX$$_00E5001C"
ON "ROOT"."AE_P_PHS_E"
("ORDER_TYPE","CATEGORY","STATUS_CODE")
COMPUTE STATISTICS;

CREATE INDEX "ROOT"."AE_P_PRO_E_IDX$$_00E5001D"
ON "ROOT"."AE_P_PRO_E"
("PROGRAM_FY","MULTITENANT_ID","PROPOSAL","BLDG")
    COMPUTE STATISTICS;

CREATE INDEX "ROOT"."AE_P_PRO_E_IDX$$_00E5001E"
    ON "ROOT"."AE_P_PRO_E"
    ("MULTITENANT_ID","BLDG","PROPOSAL","ENT_DATE" DESC ,"DESCRIPTION","ENT_CLERK","ORDER_TYPE","CATEGORY","LONG_DESC","STATUS_CODE","REGION_CODE","FAC_ID","LATITUDE","LONGITUDE","LINK_TRANX_NUM")
    COMPUTE STATISTICS;

CREATE INDEX "ROOT"."AE_P_PRO_E_IDX$$_00E5001F"
    ON "ROOT"."AE_P_PRO_E"
    ("BLDG","MULTITENANT_ID","DESCRIPTION","ENT_CLERK","ENT_DATE","PROPOSAL","ORDER_TYPE","CATEGORY","LONG_DESC","STATUS_CODE","REGION_CODE","FAC_ID","LATITUDE","LONGITUDE","LINK_TRANX_NUM")
    COMPUTE STATISTICS;

CREATE INDEX "ROOT"."AE_P_PRO_E_IDX$$_00E50020"
    ON "ROOT"."AE_P_PRO_E"
    ("MULTITENANT_ID","BLDG","CATEGORY","PROPOSAL","DESCRIPTION","ENT_CLERK","ENT_DATE","ORDER_TYPE","LONG_DESC","STATUS_CODE","REGION_CODE","FAC_ID","LATITUDE","LONGITUDE","LINK_TRANX_NUM")
    COMPUTE STATISTICS;

CREATE INDEX "ROOT"."AE_P_PHS_E_IDX$$_00E50021"
    ON "ROOT"."AE_P_PHS_E"
    ("LOCATION_CODE","MULTITENANT_ID","PROPOSAL")
    COMPUTE STATISTICS;

CREATE INDEX "ROOT"."AE_P_PRO_E_IDX$$_00E50022"
    ON "ROOT"."AE_P_PRO_E"
    ("MULTITENANT_ID","BLDG","PROPOSAL","DESCRIPTION","ENT_CLERK","ENT_DATE","ORDER_TYPE","CATEGORY","LONG_DESC","STATUS_CODE","REGION_CODE","FAC_ID","LATITUDE","LONGITUDE","LINK_TRANX_NUM")
    COMPUTE STATISTICS;

CREATE INDEX "ROOT"."AE_P_PRO_E_IDX$$_00E50023"
    ON "ROOT"."AE_P_PRO_E"
    ("STATUS_CODE","MULTITENANT_ID","CATEGORY","PROGRAM_FY","PROPOSAL","BLDG")
    COMPUTE STATISTICS;

CREATE INDEX "ROOT"."AE_P_PHS_E_IDX$$_00E50024"
    ON "ROOT"."AE_P_PHS_E"
    ("SHOP","MULTITENANT_ID","PROPOSAL")
    COMPUTE STATISTICS;

CREATE INDEX "ROOT"."AE_P_PRO_E_IDX$$_00E50025"
    ON "ROOT"."AE_P_PRO_E"
    ("MULTITENANT_ID","BLDG","CATEGORY","PROPOSAL","PROPOSAL" DESC ,"DESCRIPTION","STATUS_CODE","ORDER_TYPE","REGION_CODE","FAC_ID","ENT_DATE","LATITUDE","LONGITUDE","LINK_TRANX_NUM")
    COMPUTE STATISTICS;

CREATE INDEX "ROOT"."AE_
P_PRO_E_IDX$$_00E50026"
    ON "ROOT"."AE_P_PRO_E"
    ("PROBLEM_CODE","PROGRAM_FY")
    COMPUTE STATISTICS;

CREATE INDEX "ROOT"."AE_P_PRO_E_IDX$$_00E50027"
    ON "ROOT"."AE_P_PRO_E"
    ("REFERENCE_NO","MULTITENANT_ID")
    COMPUTE STATISTICS;

CREATE INDEX "ROOT"."AE_P_PRO_E_IDX$$_00E50028"
    ON "ROOT"."AE_P_PRO_E"
    ("BLDG","PROBLEM_CODE","DESCRIPTION","ENT_CLERK","FAC_ID")
    COMPUTE STATISTICS;

CREATE INDEX "ROOT"."AE_P_PRO_E_IDX$$_00E50029"
    ON "ROOT"."AE_P_PRO_E"
    ("BLDG","PROGRAM_FY","MULTITENANT_ID","DESCRIPTION")
    COMPUTE STATISTICS;

CREATE INDEX "ROOT"."AE_P_PRO_E_IDX$$_00E5002A"
    ON "ROOT"."AE_P_PRO_E"
    ("BLDG","MULTITENANT_ID","ENT_DATE","OC_CODE")
    COMPUTE STATISTICS;

CREATE INDEX "ROOT"."AE_P_PRO_E_IDX$$_00E5002B"
    ON "ROOT"."AE_P_PRO_E"
    ("ENT_CLERK","MULTITENANT_ID","PROJECT","CONTACT_PH","CONTACT_MC","PROBLEM_CODE","DESCRIPTION")
    COMPUTE STATISTICS;

CREATE INDEX "ROOT"."AE_P_PRO_E_IDX$$_00E5002C"
    ON "ROOT"."AE_P_PRO_E"
    ("DOC_NO","MULTITENANT_ID")
    COMPUTE STATISTICS;

CREATE INDEX "ROOT"."AE_P_PRO_E_IDX$$_00E5002D"
    ON "ROOT"."AE_P_PRO_E"
    ("ENT_CLERK","CONTACT")
    COMPUTE STATISTICS;

CREATE INDEX "ROOT"."AE_P_PRO_E_IDX$$_00E5002E"
    ON "ROOT"."AE_P_PRO_E"
    ("BLDG","MULTITENANT_ID","ENT_DATE","PROPOSAL")
    COMPUTE STATISTICS;

CREATE INDEX "ROOT"."AE_P_PRO_E_IDX$$_00E5002F"
    ON "ROOT"."AE_P_PRO_E"
    ("MULTITENANT_ID","PROPOSAL","DESCRIPTION","STATUS_CODE","ORDER_TYPE","CATEGORY","REGION_CODE","FAC_ID","BLDG","ENT_DATE","LATITUDE","LONGITUDE","LINK_TRANX_NUM")
    COMPUTE STATISTICS;

CREATE INDEX "ROOT"."AE_P_PHS_E_IDX$$_00E50030"
    ON "ROOT"."AE_P_PHS_E"
    ("MULTITENANT_ID","SHOP","LOCATION_CODE","PROPOSAL")
    COMPUTE STATISTICS;

CREATE INDEX "ROOT"."AE_P_PRO_E_IDX$$_00E50031"
    ON "ROOT"."AE_P_PRO_E"
    ("OC_CODE","MULTITENANT_ID","ENT_DATE","PROGRAM_FY")
    COMPUTE STATISTICS;

CREATE INDEX "ROOT"."PAP_TC3_PUNCH_IDX$$_00E50032"
    ON "ROOT"."PAP_TC3_PUNCH"
    ("APPROVED_DATE",TO_NUMBER("ISACTIVE"),"CONFIRMED_DATE","ISACTIVE","UMID")
    COMPUTE STATISTICS;

CREATE INDEX "ROOT"."AE_H_EMP_POS_DA_IDX$$_00E50033"
    ON "ROOT"."AE_H_EMP_POS_DATA"
    ("U_NUM","MULTITENANT_ID")
    COMPUTE STATISTICS;

CREATE BITMAP INDEX "ROOT"."AE_H_EMP_POS_DA_IDX$$_00E50034"
    ON "ROOT"."AE_H_EMP_POS_DATA"
    ("MULTITENANT_ID")
    COMPUTE STATISTICS;

CREATE INDEX "ROOT"."AE_H_EMP_E_IDX$$_00E50035"
    ON "ROOT"."AE_H_EMP_E"
    ("MULTITENANT_ID","ACTIVE","SHOP_PERSON","USER_ID")
    COMPUTE STATISTICS;

CREATE INDEX "ROOT"."PAP_TC3_TIMECAR_IDX$$_00E50036"
    ON "ROOT"."PAP_TC3_TIMECARD"
    ("ISACTIVE","PUNCH_ID")
    COMPUTE STATISTICS;

CREATE BITMAP INDEX "ROOT"."AE_P_WKA_E_IDX$$_00E50037"
    ON "ROOT"."AE_P_WKA_E"
    ("ENTRY_CLERK")
    COMPUTE STATISTICS;

CREATE INDEX "ROOT"."PAP_TC3_PUNCH_IDX$$_00E50038"
    ON "ROOT"."PAP_TC3_PUNCH"
    ("UMID")
    COMPUTE STATISTICS;

CREATE BITMAP INDEX "ROOT"."PAP_TC3_PUNCH_IDX$$_00E50039"
    ON "ROOT"."PAP_TC3_PUNCH"
    ("ISACTIVE")
    COMPUTE STATISTICS;

CREATE INDEX "ROOT"."AE_P_PHS_E_IDX$$_00E5003A"
    ON "ROOT"."AE_P_PHS_E"
    ("STATUS_CODE","PRI_CODE","MULTITENANT_ID","PROPOSAL")
    COMPUTE STATISTICS;

CREATE INDEX "ROOT"."AE_P_PHS_E_IDX$$_00E5003B"
    ON "ROOT"."AE_P_PHS_E"
    ("EDIT_CLERK","STATUS_CODE","PRI_CODE","MULTITENANT_ID","PROPOSAL")
    COMPUTE STATISTICS;

CREATE INDEX "ROOT"."AE_P_REQ_E_IDX$$_00E5003C"
    ON "ROOT"."AE_P_REQ_E"
    ("DOC_NO","OC_CODE","REQUESTOR","DESIRED_DATE","PROBLEM_CODE","DESCRIPTION","STATUS_CODE","BLDG","CONTACT","CONTACT_PH","LINK_TRANX_NUM","MULTITENANT_ID")
    COMPUTE STATISTICS;

CREATE INDEX "ROOT"."AE_I_PRE_E_IDX$$_00E5003D"
    ON "ROOT"."AE_I_PRE_E"
    ("PROPOSAL","SORT_CODE","MULTITENANT_ID","PR_CODE","DATE_NEEDED","PLACEDBY","PR_STATUS","REGION_CODE","FAC_ID","BLDG","LOCATION_CODE","LOC_ID","SHOP_PERSON","LINK_TRANX_NUM")
    COMPUTE STATISTICS;

CREATE INDEX "ROOT"."AE_P_REQ_E_IDX$$_00E5003E"
    ON "ROOT"."AE_P_REQ_E"
   
("STATUS_CODE","MULTITENANT_ID","DOC_NO","OC_CODE","REQUESTOR","DESIRED_DATE","PROBLEM_CODE","DESCRIPTION","BLDG","CONTACT","CONTACT_PH","LINK_TRANX_NUM","ENT_DATE","EDIT_CLERK")
COMPUTE STATISTICS;

CREATE INDEX "ROOT"."AE_DOCUMENT_VER_IDX$$_00E5003F"
ON "ROOT"."AE_DOCUMENT_VERSION"
("DOC_VER_ID","MULTITENANT_ID")
COMPUTE STATISTICS;

CREATE INDEX "ROOT"."AE_A_ASSET_E_IDX$$_00E50041"
ON "ROOT"."AE_A_ASSET_E"
("ASSET_GROUP","MULTITENANT_ID","ASSET_TAG","STATUS_CODE","ASSET_TYPE")
COMPUTE STATISTICS;

CREATE INDEX "ROOT"."AE_I_POE_D_IDX$$_00E50042"
ON "ROOT"."AE_I_POE_D"
("PO_CODE","MULTITENANT_ID")
COMPUTE STATISTICS;

CREATE INDEX "ROOT"."PAP_TC3_PUNCH_IDX$$_00E50044"
ON "ROOT"."PAP_TC3_PUNCH"
("APPROVED_DATE","CONFIRMED_DATE","ISACTIVE","UMID")
COMPUTE STATISTICS;

CREATE INDEX "ROOT"."AE_L_SHP_D_IDX$$_00E50047"
ON "ROOT"."AE_L_SHP_D"
("SHOP","MULTITENANT_ID","DATE_TO","SHOP_PERSON","DATE_FROM")
COMPUTE STATISTICS;

CREATE BITMAP INDEX "ROOT"."PAP_TC3_PUNCH_IDX$$_00E50048"
ON "ROOT"."PAP_TC3_PUNCH"
("WORK_DATE")
COMPUTE STATISTICS;

CREATE INDEX "ROOT"."AE_I_POE_P_IDX$$_00E5004E"
ON "ROOT"."AE_I_POE_P"
("PO_CODE","MULTITENANT_ID","PO_ITEM")
COMPUTE STATISTICS;

CREATE INDEX "ROOT"."AE_I_POE_E_IDX$$_00E5004F"
ON "ROOT"."AE_I_POE_E"
("PURCHASE_ORDER")
COMPUTE STATISTICS;

CREATE INDEX "ROOT"."AE_P_PRO_EMAIL__IDX$$_00E50058"
ON "ROOT"."AE_P_PRO_EMAIL_LOG"
("PROPOSAL","SORT_CODE")
COMPUTE STATISTICS;

CREATE INDEX "ROOT"."AE_DAILY_ASSIGN_IDX$$_00E5005D"
ON "ROOT"."AE_DAILY_ASSIGN_E"
("MULTITENANT_ID","SHOP_PERSON")
COMPUTE STATISTICS;

CREATE INDEX "ROOT"."AE_P_PRO_E_IDX$$_00E5005F"
ON "ROOT"."AE_P_PRO_E"
("BLDG","ORDER_TYPE","MULTITENANT_ID","ENT_DATE","PROPOSAL")
COMPUTE STATISTICS;

CREATE BITMAP INDEX "ROOT"."AE_X_CFT_E_IDX$$_00E50061"
ON "ROOT"."AE_X_CFT_E"
("CATEGORY")
COMPUTE STATISTICS;

CREATE BITMAP INDEX "ROOT"
."AE_X_CFT_E_IDX$$_00E50062"
ON "ROOT"."AE_X_CFT_E"
("ORDER_TYPE")
COMPUTE STATISTICS;

CREATE BITMAP INDEX "ROOT"."AE_X_CFT_E_IDX$$_00E50063"
ON "ROOT"."AE_X_CFT_E"
("MULTITENANT_ID")
COMPUTE STATISTICS;

CREATE BITMAP INDEX "ROOT"."AE_X_CFT_E_IDX$$_00E50065"
ON "ROOT"."AE_X_CFT_E"
("ACTIVE")
COMPUTE STATISTICS;

CREATE INDEX "ROOT"."AE_DAILY_ASSIGN_IDX$$_00E50066"
ON "ROOT"."AE_DAILY_ASSIGN_E"
("SHOP_PERSON","MULTITENANT_ID","SCHED_DATE","TRANS_NO")
COMPUTE STATISTICS;

CREATE INDEX "ROOT"."PAP_TC3_MESSAGE_IDX$$_00E5006B"
ON "ROOT"."PAP_TC3_MESSAGE"
(TO_NUMBER("CREATED_FOR_UMID"),"READ_DATE")
COMPUTE STATISTICS;

CREATE INDEX "ROOT"."AE_P_PRO_E_IDX$$_00E50072"
ON "ROOT"."AE_P_PRO_E"
("CATEGORY","MULTITENANT_ID","PROPOSAL")
COMPUTE STATISTICS;

CREATE INDEX "ROOT"."AE_LAYOUT_IDX$$_00E50073"
ON "ROOT"."AE_LAYOUT"
("LOGIN","MODULE_KEY")
COMPUTE STATISTICS;

CREATE INDEX "ROOT"."AE_X_CFT_E_IDX$$_00E5007A"
ON "ROOT"."AE_X_CFT_E"
("CRAFT_CODE","ACTIVE","MULTITENANT_ID")
COMPUTE STATISTICS;

CREATE INDEX "ROOT"."AE_AUTHZ_PRINCI_IDX$$_00E50082"
ON "ROOT"."AE_AUTHZ_PRINCIPAL"
("LOGIN","MULTITENANT_ID","ROLE_ID")
COMPUTE STATISTICS;

CREATE INDEX "ROOT"."AE_EST_PHS_E_IDX$$_00E50086"
ON "ROOT"."AE_EST_PHS_E"
("PROPOSAL","SORT_CODE","MULTITENANT_ID")
COMPUTE STATISTICS;

CREATE INDEX "ROOT"."AE_EST_PHS_D_IDX$$_00E50087"
ON "ROOT"."AE_EST_PHS_D"
("MULTITENANT_ID","ESTIMATE_NO")
COMPUTE STATISTICS;

CREATE INDEX "ROOT"."AE_EST_PHS_E_IDX$$_00E50089"
ON "ROOT"."AE_EST_PHS_E"
("PROPOSAL","MULTITENANT_ID","ESTIMATE_NO")
COMPUTE STATISTICS;

CREATE INDEX "ROOT"."AE_A_ASSET_E_IDX$$_00E500A3"
ON "ROOT"."AE_A_ASSET_E"
("BLDG","FAC_ID","REGION_CODE","MULTITENANT_ID","ASSET_TAG","DESCRIPTION","ASSET_TYPE","ASSET_GROUP","STATUS_CODE")
COMPUTE STATISTICS;

CREATE INDEX "ROOT"."AE_S_FLT_SUB_IDX$$_00E500B4"
ON "ROOT"."AE_S_FLT_SUB"

("FILTER_NAME","LOGIN")
COMPUTE STATISTICS;

CREATE INDEX "ROOT"."AE_CHANNEL_QS_IDX$$_00E500B5"
ON "ROOT"."AE_CHANNEL_QS"
("TRANX_NUM","MULTITENANT_ID")
COMPUTE STATISTICS;

CREATE INDEX "ROOT"."AE_REPORT_SCREE_IDX$$_00E500B8"
ON "ROOT"."AE_REPORT_SCREEN"
("SCREEN_NAME","MULTITENANT_ID")
COMPUTE STATISTICS;

CREATE INDEX "ROOT"."AE_REPORT_AUTHZ_IDX$$_00E500B9"
ON "ROOT"."AE_REPORT_AUTHZ"
("MULTITENANT_ID","ID")
COMPUTE STATISTICS;

CREATE INDEX "ROOT"."AE_S_FLT_GROUP_IDX$$_00E500C4"
ON "ROOT"."AE_S_FLT_GROUP"
("FILTER_NAME")
COMPUTE STATISTICS;

CREATE INDEX "ROOT"."AE_L_SHP_ACCOUN_IDX$$_00E500DC"
ON "ROOT"."AE_L_SHP_ACCOUNTS"
("MULTITENANT_ID","SHOP","SEQ","SUB_LEDGER","ACCOUNT_TYPE","FUNDING_CODE","SUB_CODE","END_DATE")
COMPUTE STATISTICS;