UPDATE AE_R_PME_E A 
SET A.PM_LAST_DATE = (SELECT B.PM_LAST_DATE 
FROM UM_R_PME_E B 
WHERE A.TEMPLATE_ID = B.TEMPLATE_ID AND A.ASSET_TAG = B.ASSET_TAG AND A.UNION_SEQ = B.UNION_SEQ)
WHERE EXISTS
   ( SELECT PM_LAST_DATE
     FROM UM_R_PME_E B
     WHERE A.TEMPLATE_ID = B.TEMPLATE_ID AND A.ASSET_TAG = B.ASSET_TAG AND A.UNION_SEQ = B.UNION_SEQ);
COMMIT;